
package com.sacooliveros.gepsac.proxyws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BOService", targetNamespace = "http://service.gepsac.sacooliveros.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BOService {


    /**
     * 
     * @param alumno
     * @return
     *     returns com.sacooliveros.gepsac.proxyws.EvaluacionPostulante
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "evaluarAlumno", targetNamespace = "http://service.gepsac.sacooliveros.com/", className = "com.sacooliveros.gepsac.proxyws.EvaluarAlumno")
    @ResponseWrapper(localName = "evaluarAlumnoResponse", targetNamespace = "http://service.gepsac.sacooliveros.com/", className = "com.sacooliveros.gepsac.proxyws.EvaluarAlumnoResponse")
    public EvaluacionPostulante evaluarAlumno(
        @WebParam(name = "alumno", targetNamespace = "")
        EvaluacionPostulante alumno);

}
