
package com.sacooliveros.gepsac.proxyws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CommonService", targetNamespace = "http://service.gepsac.sacooliveros.com/", wsdlLocation = "file:/D:/rcastillejo/Documentos/PI2/fuentes/sacooliveros-gepsac/gepsac/gepsac-proxyws/src/wsdl/CommonService.xml")
public class CommonService_Service
    extends Service
{

    private final static URL COMMONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sacooliveros.gepsac.proxyws.CommonService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sacooliveros.gepsac.proxyws.CommonService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/rcastillejo/Documentos/PI2/fuentes/sacooliveros-gepsac/gepsac/gepsac-proxyws/src/wsdl/CommonService.xml");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/rcastillejo/Documentos/PI2/fuentes/sacooliveros-gepsac/gepsac/gepsac-proxyws/src/wsdl/CommonService.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COMMONSERVICE_WSDL_LOCATION = url;
    }

    public CommonService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonService_Service() {
        super(COMMONSERVICE_WSDL_LOCATION, new QName("http://service.gepsac.sacooliveros.com/", "CommonService"));
    }

    /**
     * 
     * @return
     *     returns CommonService
     */
    @WebEndpoint(name = "CommonServicePort")
    public CommonService getCommonServicePort() {
        return super.getPort(new QName("http://service.gepsac.sacooliveros.com/", "CommonServicePort"), CommonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonService
     */
    @WebEndpoint(name = "CommonServicePort")
    public CommonService getCommonServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.gepsac.sacooliveros.com/", "CommonServicePort"), CommonService.class, features);
    }

}
