
package com.sacooliveros.gepsac.proxyws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ExpertoWebService", targetNamespace = "http://experto.service.gepsac.sacooliveros.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExpertoWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sacooliveros.gepsac.proxyws.EvaluacionPostulante
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "evaluarAlumno", targetNamespace = "http://experto.service.gepsac.sacooliveros.com/", className = "com.sacooliveros.gepsac.proxyws.EvaluarAlumno")
    @ResponseWrapper(localName = "evaluarAlumnoResponse", targetNamespace = "http://experto.service.gepsac.sacooliveros.com/", className = "com.sacooliveros.gepsac.proxyws.EvaluarAlumnoResponse")
    public EvaluacionPostulante evaluarAlumno(
        @WebParam(name = "arg0", targetNamespace = "")
        Alumno arg0)
        throws ServiceException_Exception
    ;

}
