
package com.sacooliveros.gepsac.proxyws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebServiceAlumno", targetNamespace = "http://app.sacoliveros.pe.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceAlumno {


    /**
     * 
     * @param codigo
     * @return
     *     returns com.sacooliveros.gepsac.proxyws.Alumno
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerAlumnoPostulante", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "com.sacooliveros.gepsac.proxyws.ObtenerAlumnoPostulante")
    @ResponseWrapper(localName = "obtenerAlumnoPostulanteResponse", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "com.sacooliveros.gepsac.proxyws.ObtenerAlumnoPostulanteResponse")
    public Alumno obtenerAlumnoPostulante(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo);

    /**
     * 
     * @return
     *     returns java.util.List<com.sacooliveros.gepsac.proxyws.Alumno>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarAlumnoPostulante", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "com.sacooliveros.gepsac.proxyws.ListarAlumnoPostulante")
    @ResponseWrapper(localName = "listarAlumnoPostulanteResponse", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "com.sacooliveros.gepsac.proxyws.ListarAlumnoPostulanteResponse")
    public List<Alumno> listarAlumnoPostulante();

    /**
     * 
     * @param codigo
     * @param nombres
     * @param apellidos
     * @return
     *     returns java.util.List<com.sacooliveros.gepsac.proxyws.Alumno>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarAlumnoPostulante", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "com.sacooliveros.gepsac.proxyws.BuscarAlumnoPostulante")
    @ResponseWrapper(localName = "buscarAlumnoPostulanteResponse", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "com.sacooliveros.gepsac.proxyws.BuscarAlumnoPostulanteResponse")
    public List<Alumno> buscarAlumnoPostulante(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombres", targetNamespace = "")
        String nombres,
        @WebParam(name = "apellidos", targetNamespace = "")
        String apellidos);

}
