
package edu.pe.sacoliveros.app;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebServiceAlumno", targetNamespace = "http://app.sacoliveros.pe.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceAlumno {


    /**
     * 
     * @param codigo
     * @return
     *     returns edu.pe.sacoliveros.app.Alumno
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerAlumnoPostulante", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.ObtenerAlumnoPostulante")
    @ResponseWrapper(localName = "obtenerAlumnoPostulanteResponse", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.ObtenerAlumnoPostulanteResponse")
    public Alumno obtenerAlumnoPostulante(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo);

    /**
     * 
     * @param codigo
     * @param nombres
     * @param apellidos
     * @return
     *     returns java.util.List<edu.pe.sacoliveros.app.Alumno>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarAlumnoEvaluado", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.BuscarAlumnoEvaluado")
    @ResponseWrapper(localName = "buscarAlumnoEvaluadoResponse", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.BuscarAlumnoEvaluadoResponse")
    public List<Alumno> buscarAlumnoEvaluado(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombres", targetNamespace = "")
        String nombres,
        @WebParam(name = "apellidos", targetNamespace = "")
        String apellidos);

    /**
     * 
     * @return
     *     returns java.util.List<edu.pe.sacoliveros.app.Alumno>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarAlumnoPostulante", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.ListarAlumnoPostulante")
    @ResponseWrapper(localName = "listarAlumnoPostulanteResponse", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.ListarAlumnoPostulanteResponse")
    public List<Alumno> listarAlumnoPostulante();

    /**
     * 
     * @param codigo
     * @param nombres
     * @param apellidos
     * @return
     *     returns java.util.List<edu.pe.sacoliveros.app.Alumno>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarAlumnoPostulante", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.BuscarAlumnoPostulante")
    @ResponseWrapper(localName = "buscarAlumnoPostulanteResponse", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.BuscarAlumnoPostulanteResponse")
    public List<Alumno> buscarAlumnoPostulante(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombres", targetNamespace = "")
        String nombres,
        @WebParam(name = "apellidos", targetNamespace = "")
        String apellidos);

    /**
     * 
     * @param codigo
     * @return
     *     returns edu.pe.sacoliveros.app.Alumno
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerAlumnoEvaluacion", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.ObtenerAlumnoEvaluacion")
    @ResponseWrapper(localName = "obtenerAlumnoEvaluacionResponse", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.ObtenerAlumnoEvaluacionResponse")
    public Alumno obtenerAlumnoEvaluacion(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo);

    /**
     * 
     * @return
     *     returns java.util.List<edu.pe.sacoliveros.app.Alumno>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarAlumnoEvaluado", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.ListarAlumnoEvaluado")
    @ResponseWrapper(localName = "listarAlumnoEvaluadoResponse", targetNamespace = "http://app.sacoliveros.pe.edu/", className = "edu.pe.sacoliveros.app.ListarAlumnoEvaluadoResponse")
    public List<Alumno> listarAlumnoEvaluado();

}
