
package com.sacooliveros.gepsac.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BOService", targetNamespace = "http://service.gepsac.sacooliveros.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BOService {


    /**
     * 
     * @param evaluacionPostulante
     * @return
     *     returns com.sacooliveros.gepsac.service.EvaluacionPostulante
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "evaluarAlumno", targetNamespace = "http://service.gepsac.sacooliveros.com/", className = "com.sacooliveros.gepsac.service.EvaluarAlumno")
    @ResponseWrapper(localName = "evaluarAlumnoResponse", targetNamespace = "http://service.gepsac.sacooliveros.com/", className = "com.sacooliveros.gepsac.service.EvaluarAlumnoResponse")
    public EvaluacionPostulante evaluarAlumno(
        @WebParam(name = "evaluacionPostulante", targetNamespace = "")
        EvaluacionPostulante evaluacionPostulante);

    /**
     * 
     * @param codigoEvaluacionAcosoEscolar
     * @return
     *     returns com.sacooliveros.gepsac.service.ExplicacionResultado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "explicacion", targetNamespace = "http://service.gepsac.sacooliveros.com/", className = "com.sacooliveros.gepsac.service.Explicacion")
    @ResponseWrapper(localName = "explicacionResponse", targetNamespace = "http://service.gepsac.sacooliveros.com/", className = "com.sacooliveros.gepsac.service.ExplicacionResponse")
    public ExplicacionResultado explicacion(
        @WebParam(name = "codigoEvaluacionAcosoEscolar", targetNamespace = "")
        String codigoEvaluacionAcosoEscolar);

}
