
package com.sacooliveros.gepsac.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BOService", targetNamespace = "http://service.gepsac.sacooliveros.com/", wsdlLocation = "http://localhost:8180/gepsac-service/BOService?wsdl")
public class BOService_Service
    extends Service
{

    private final static URL BOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sacooliveros.gepsac.service.BOService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sacooliveros.gepsac.service.BOService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8180/gepsac-service/BOService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8180/gepsac-service/BOService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BOSERVICE_WSDL_LOCATION = url;
    }

    public BOService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BOService_Service() {
        super(BOSERVICE_WSDL_LOCATION, new QName("http://service.gepsac.sacooliveros.com/", "BOService"));
    }

    /**
     * 
     * @return
     *     returns BOService
     */
    @WebEndpoint(name = "BOServicePort")
    public BOService getBOServicePort() {
        return super.getPort(new QName("http://service.gepsac.sacooliveros.com/", "BOServicePort"), BOService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BOService
     */
    @WebEndpoint(name = "BOServicePort")
    public BOService getBOServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.gepsac.sacooliveros.com/", "BOServicePort"), BOService.class, features);
    }

}
