create or replace
FUNCTION GET_TOKEN(
   THE_LIST  VARCHAR2,
   THE_INDEX NUMBER,
   DELIM     VARCHAR2 := ','
)
   RETURN    VARCHAR2
IS
   START_POS NUMBER;
   END_POS   NUMBER;
BEGIN
   IF THE_INDEX = 1 THEN
       START_POS := 1;
   ELSE
       START_POS := INSTR(THE_LIST, DELIM, 1, THE_INDEX - 1);
       IF START_POS = 0 THEN
           RETURN NULL;
       ELSE
           START_POS := START_POS + LENGTH(DELIM);
       END IF;
   END IF;

   END_POS := INSTR(THE_LIST, DELIM, START_POS, 1);

   IF END_POS = 0 THEN
       RETURN SUBSTR(THE_LIST, START_POS);
   ELSE
       RETURN SUBSTR(THE_LIST, START_POS, END_POS - START_POS);
   END IF;

END GET_TOKEN;