create or replace
PACKAGE BODY "PKG_SCA" AS

/*
==========================
STORE PROCEDURE DE TEMPLATE
===========================*/

PROCEDURE SPD_ELIMINAR_TEMPLATE(
  IS_ID_TEMPLATE IN VARCHAR2,
  OS_COD_RETORNO  OUT VARCHAR2,
  OS_MEN_RETORNO  OUT VARCHAR2
)
IS
BEGIN
  DELETE FROM TP_TEMPLATE WHERE ID_TEMPLATE = TO_NUMBER(IS_ID_TEMPLATE);
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;

PROCEDURE SPU_ACTUALIZAR_TEMPLATE(
IS_ID_TEMPLATE IN VARCHAR2,
IS_NOMBRE      IN VARCHAR2,
IS_DESCRIPCION IN VARCHAR2,
IS_USUARIO     IN VARCHAR2,
OS_COD_RETORNO  OUT VARCHAR2,
OS_MEN_RETORNO  OUT VARCHAR2
)
IS 
BEGIN
  
  UPDATE TP_TEMPLATE SET NOMBRE = IS_NOMBRE, DESCRIPCION = IS_DESCRIPCION, AUD_USU_MODIF = IS_USUARIO,  AUD_FEC_MODIF = SYSDATE 
  WHERE ID_TEMPLATE = IS_ID_TEMPLATE;

  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;

PROCEDURE SPS_CONSULTAR_TEMPLATE(
  IS_ID_TEMPLATE IN VARCHAR2,
  OS_COD_RETORNO  OUT VARCHAR2,
  OS_MEN_RETORNO  OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
)
IS
  T_QUERY VARCHAR2(500);
BEGIN
  
  T_QUERY := 'SELECT ID_TEMPLATE, MNEMONICO, NOMBRE, TIPO, DESCRIPCION FROM TP_TEMPLATE WHERE ID_TEMPLATE = ' || IS_ID_TEMPLATE;

  OPEN OS_CURSOR FOR T_QUERY;

  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;


PROCEDURE SPS_CONSULTAR_TEMPLATES(
  IS_ID_EMPRESA     IN VARCHAR2,
  IS_ID_APLICACION  IN VARCHAR2,
  IS_NOMBRE         IN VARCHAR2,
  IS_TIPO           IN VARCHAR2,
  OS_COD_RETORNO  OUT VARCHAR2,
  OS_MEN_RETORNO  OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
)
IS
  T_QUERY VARCHAR2(500);
BEGIN 

  T_QUERY := 'SELECT ID_TEMPLATE, NOMBRE, TIPO, DESCRIPCION FROM TP_TEMPLATE WHERE 1=1 ';
  
  IF IS_TIPO <> '-1' THEN
    T_QUERY := T_QUERY || ' AND TIPO = ''' || IS_TIPO || '''';
  END IF;
  
  IF IS_NOMBRE IS NOT NULL THEN
    T_QUERY := T_QUERY || ' AND NOMBRE LIKE ''' || IS_NOMBRE || '%''';
  END IF;
  
  IF IS_ID_EMPRESA IS NOT NULL THEN
    T_QUERY := T_QUERY || ' AND MNEMONICO = ''' || IS_ID_EMPRESA || '''';
  END IF;

  IF IS_ID_APLICACION IS NOT NULL THEN
    T_QUERY := T_QUERY || ' AND MNEMONICO = ''' || IS_ID_APLICACION || '''';
  END IF;
  
  OPEN OS_CURSOR FOR T_QUERY;

  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;


/*
==========================
STORE PROCEDURE DE AUDITORIA
===========================*/

PROCEDURE SPS_CONSULTAR_DETALLE_AUD(
IS_ID_AUDITORIA        IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
  T_QUERY VARCHAR2(400);
BEGIN
  T_QUERY := 'SELECT VALORES_ANTIGUOS AS ANTIGUO, VALORES_NUEVOS AS NUEVO FROM TP_AUDITORIA WHERE ID_AUDITORIA =' || TO_NUMBER(IS_ID_AUDITORIA);
  
  OPEN OS_CURSOR FOR T_QUERY;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;


PROCEDURE SPS_CONSULTAR_AUDITORIA(
IS_USUARIO             IN VARCHAR2,
IS_METODO              IN VARCHAR2,
IS_IP                  IN VARCHAR2,
IS_EMPRESA          IN VARCHAR2,
IS_FECHA_INICIO        IN VARCHAR2,
IS_FECHA_FIN           IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS 
T_QUERY VARCHAR2(1000);
BEGIN
  
  T_QUERY := 'SELECT ID_AUDITORIA AS ID, TO_CHAR(FECHA, ''dd/MM/yyyy HH:mm:ss'') AS FECHA, USUARIO, MENU, CLASE, METODO, MODULO, IP FROM TP_AUDITORIA WHERE 1=1';
  
  IF IS_USUARIO IS NOT NULL THEN
    T_QUERY := T_QUERY || ' AND USUARIO = ''' || IS_USUARIO || '''';
  END IF;
  
  IF TRIM(IS_METODO) IS NOT NULL THEN
    T_QUERY := T_QUERY || ' AND METODO = ''' || IS_METODO || '''';
  END IF;
  
  IF TRIM(IS_IP) IS NOT NULL THEN
    T_QUERY := T_QUERY || ' AND IP = ''' || IS_IP || '''';
  END IF;
  
  IF TRIM(IS_EMPRESA) IS NOT NULL AND IS_EMPRESA <> '-1' THEN
    T_QUERY := T_QUERY || ' AND EMPRESA = ''' || IS_EMPRESA || '''';
  END IF;
  
  IF (TRIM(IS_FECHA_INICIO) IS NOT NULL) AND (TRIM(IS_FECHA_FIN) IS NOT NULL)  THEN
    T_QUERY := T_QUERY || ' AND TO_DATE(TO_CHAR(FECHA,''DD/MM/YYYY''), ''DD/MM/YYYY'') BETWEEN TO_DATE(''' || IS_FECHA_INICIO || ''', ''DD/MM/YYYY'') AND TO_DATE(''' || IS_FECHA_FIN || ''', ''DD/MM/YYYY'')' ;
  ELSIF TRIM(IS_FECHA_INICIO) IS NOT NULL THEN
    T_QUERY := T_QUERY || ' AND TO_CHAR(FECHA,''DD/MM/YYYY'') = ''' || IS_FECHA_INICIO || '''';
  ELSIF TRIM(IS_FECHA_FIN) IS NOT NULL THEN
    T_QUERY := T_QUERY || ' AND TO_CHAR(FECHA,''DD/MM/YYYY'') = ''' || IS_FECHA_FIN || '''';
  END IF;
  
  OPEN OS_CURSOR FOR T_QUERY;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;

/*
==========================
STORE PROCEDURE DE LOGIN
===========================*/

PROCEDURE SPS_CONSULTAR_CREDENCIALES(
IS_USUARIO            IN VARCHAR2,
OS_COD_RETORNO        OUT VARCHAR2,
OS_MEN_RETORNO        OUT VARCHAR2,
OS_CURSOR             OUT T_CURSOR
)
IS
V_CURSOR      T_CURSOR;
T_QUERY       VARCHAR2(1000);
BEGIN
   
  T_QUERY := ' SELECT e.ID_EMPRESA,e.MNEMONICO AS EMPRESA,ID_USUARIO,USUARIO,CONTRASENA,u.NOMBRE,APELLIDOPATERNO, ' ||
             ' APELLIDOMATERNO,CORREO,u.ESTADO,TIPODOCUMENTO,NUMERODOCUMENTO,TELEFONO,' ||
             ' TO_CHAR(FECHA_CAMBIO_CLAVE, ''yyyy-MM-dd HH:mm:ss'') AS FECHA_CAMBIO_CLAVE,TO_CHAR(FECHA_LOGIN, ''yyyy-MM-dd HH:mm:ss'') AS  FECHA_LOGIN,MAC ' ||
             ' FROM TP_USUARIO u LEFT JOIN TP_EMPRESA e ON u.ID_EMPRESA=e.ID_EMPRESA ' ||
             ' WHERE 1=1';
              
   IF IS_USUARIO IS NOT NULL THEN
     T_QUERY := T_QUERY || ' AND USUARIO = ''' || IS_USUARIO || '''';
   END IF;
      
   OPEN OS_CURSOR FOR T_QUERY;
      
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


/*
==========================
STORE PROCEDURE DE EMPRESA
===========================*/
PROCEDURE SPS_CONSULTAR_EMPRESA_DATA(
  IS_TIPO IN NUMBER,
  OS_COD_RETORNO       OUT VARCHAR2,
  OS_MEN_RETORNO       OUT VARCHAR2,
  OS_CURSOR            OUT T_CURSOR
)
IS
BEGIN
  IF IS_TIPO = 1 THEN
    OPEN OS_CURSOR FOR SELECT ID_EMPRESA AS CODIGO, NOMBRE FROM TP_EMPRESA;
  ELSE 
    OPEN OS_CURSOR FOR SELECT MNEMONICO AS CODIGO, NOMBRE FROM TP_EMPRESA;
  END IF;
  
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Empresas consultadas correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
  
END;

PROCEDURE SPI_REGISTRAR_EMPRESA(
IS_MNEMONICO IN VARCHAR2,
IS_NOMBRE IN VARCHAR2,
IS_DESCRIPCION IN VARCHAR2,
IS_ESTADO IN VARCHAR2,
IS_USUARIO IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,

OS_MEN_RETORNO           OUT VARCHAR2,
OS_COD_EMPRESA           OUT NUMBER
)
IS
  CONT NUMBER;
BEGIN
 
 SELECT COUNT(1) INTO CONT FROM TP_EMPRESA WHERE MNEMONICO = IS_MNEMONICO;

 IF CONT = 0 THEN 

 INSERT INTO TP_EMPRESA(
                ID_EMPRESA,
                MNEMONICO,
                NOMBRE,
                DESCRIPCION,
                ESTADO,
        AUD_FEC_CREAC,
        AUD_USU_CREAC
                )
            VALUES(
                SEQ_EMPRESA.NEXTVAL,
                IS_MNEMONICO,
                IS_NOMBRE,
                IS_DESCRIPCION,
                IS_ESTADO, SYSDATE, IS_USUARIO) RETURNING ID_EMPRESA INTO OS_COD_EMPRESA;             
                
    INSERT INTO TS_ATRIBUTO_EMPRESA(ID_POLITICA,ID_ATRIBUTO, EMPRESA,VALOR)
                                    SELECT ID_POLITICA, ID_ATRIBUTO, IS_MNEMONICO, VALOR FROM TS_ATRIBUTO_EMPRESA
                                      WHERE EMPRESA = (SELECT MNEMONICO FROM TP_EMPRESA WHERE ID_EMPRESA = 1);
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Empresa registrada correctamente.';
ELSE
  OS_COD_RETORNO := '10';
  OS_MEN_RETORNO := 'La empresa ya existe';
END IF;


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;          

END;

PROCEDURE SPU_ACTUALIZAR_EMPRESA(
IS_ID_EMPRESA   IN NUMBER,
IS_NOMBRE     IN VARCHAR2,
IS_DESCRIPCION  IN VARCHAR2,
IS_ESTADO     IN VARCHAR2,
IS_USUARIO      IN VARCHAR2,
OS_COD_RETORNO  OUT VARCHAR2,
OS_MEN_RETORNO  OUT VARCHAR2
)
IS

BEGIN

 UPDATE TP_EMPRESA SET NOMBRE = IS_NOMBRE,
                       DESCRIPCION = IS_DESCRIPCION,
                       ESTADO = IS_ESTADO,
             AUD_FEC_MODIF = SYSDATE,
             AUD_USU_MODIF = IS_USUARIO
             WHERE ID_EMPRESA = IS_ID_EMPRESA;
                
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Empresa actualizada correctamente.';


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPD_ELIMINAR_EMPRESA(
IS_ID_EMPRESA IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2

)
IS
EX_NO_DELETE exception;
pragma exception_init (EX_NO_DELETE,-02292);

BEGIN

 DELETE TS_ATRIBUTO_EMPRESA WHERE EMPRESA = (SELECT MNEMONICO FROM TP_EMPRESA WHERE ID_EMPRESA = IS_ID_EMPRESA);
 DELETE TP_EMPRESA WHERE ID_EMPRESA= IS_ID_EMPRESA;             
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Empresa eliminada correctamente.';

EXCEPTION
WHEN EX_NO_DELETE THEN
    OS_COD_RETORNO := '30';
    OS_MEN_RETORNO := 'La empresa no puede ser eliminada porque se encuentra asociada a un usuario / aplicaci&oacute;n.';


WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_EMPRESA(
IS_ID_EMPRESA          IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
V_CURSOR T_CURSOR;

BEGIN
   
   OPEN V_CURSOR FOR
    SELECT ID_EMPRESA,
	  MNEMONICO,
	  NOMBRE,
	  ESTADO,
	  DESCRIPCION
		FROM TP_EMPRESA 
    WHERE ID_EMPRESA = IS_ID_EMPRESA;             
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_CONSULTAR_EMPRESA_TODAS(
IS_NOMBRE VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
V_CURSOR T_CURSOR;

BEGIN

   IF IS_NOMBRE IS NULL THEN
     T_QUERY := 'SELECT ID_EMPRESA, MNEMONICO, NOMBRE, DESCRIPCION, ESTADO FROM TP_EMPRESA';     
      ELSE
   T_QUERY := 'SELECT ID_EMPRESA, MNEMONICO, NOMBRE, DESCRIPCION, ESTADO FROM TP_EMPRESA WHERE NOMBRE LIKE '''||IS_NOMBRE || '%''' ;  
    END IF;
   
   OPEN V_CURSOR FOR T_QUERY;
     OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


/*
==========================
STORE PROCEDURE DE USUARIO
===========================*/
PROCEDURE SPS_USUARIO_CAMBIAR_PASS(
IS_ID_USUARIO       IN NUMBER,
IS_MAC              IN VARCHAR2,
IS_PASSWORD         IN VARCHAR2,
IS_USUARIO      IN VARCHAR2,
OS_EMAIL            OUT VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2
)
IS

BEGIN
  UPDATE TP_USUARIO SET CONTRASENA = IS_PASSWORD, ESTADO = 'RESETEADO', MAC = IS_MAC, AUD_FEC_MODIF = SYSDATE, AUD_USU_MODIF = IS_USUARIO 
  WHERE ID_USUARIO=IS_ID_USUARIO;
  
  SELECT CORREO INTO OS_EMAIL FROM TP_USUARIO WHERE ID_USUARIO=IS_ID_USUARIO;
  COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Usuario modificado correctamente.';


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;

PROCEDURE SPI_REGISTRAR_USUARIO(
IS_ID_EMPRESA IN NUMBER,
IS_USUARIO IN VARCHAR2,
IS_CONTRASENA IN VARCHAR2,
IS_APELLIDOMATERNO IN VARCHAR2,
IS_APELLIDOPATERNO IN VARCHAR2,
IS_NOMBRE IN VARCHAR2,
IS_CORREO IN VARCHAR2,
IS_ESTADO IN VARCHAR,
IS_TIPODOCUMENTO IN VARCHAR2,
IS_NUMERODOCUMENTO IN VARCHAR2,
IS_TELEFONO IN VARCHAR2,
IS_FECHACAMBIOCLAVE IN TIMESTAMP,
IS_FECHALOGIN IN TIMESTAMP,
IS_MAC IN VARCHAR2,
IS_USUARIO_AGR  IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_ID_USUARIO            OUT NUMBER
)
IS
 CONT NUMBER;
 EMPRESA VARCHAR2(200);
BEGIN
  
  SELECT COUNT(1) INTO CONT FROM TP_USUARIO WHERE USUARIO = IS_USUARIO;
  
  IF CONT = 0 THEN 

 INSERT INTO TP_USUARIO(
                ID_EMPRESA,
                ID_USUARIO,
                USUARIO,
                CONTRASENA,
                APELLIDOMATERNO,
                APELLIDOPATERNO,
                NOMBRE,
                CORREO,
                ESTADO,
                TIPODOCUMENTO,
                NUMERODOCUMENTO,
                TELEFONO,
                FECHA_CAMBIO_CLAVE,
                FECHA_LOGIN,
                MAC,
        AUD_FEC_CREAC,
        AUD_USU_CREAC)
            VALUES(
                IS_ID_EMPRESA,
                SEQ_USUARIO.NEXTVAL,
                IS_USUARIO,
                IS_CONTRASENA,
                IS_APELLIDOMATERNO,
                IS_APELLIDOPATERNO,
                IS_NOMBRE,
                IS_CORREO,
                IS_ESTADO,
                IS_TIPODOCUMENTO,
                IS_NUMERODOCUMENTO,
                IS_TELEFONO,
                IS_FECHACAMBIOCLAVE,
                IS_FECHALOGIN,
                IS_MAC,
        SYSDATE,
        IS_USUARIO_AGR) RETURNING ID_USUARIO INTO OS_ID_USUARIO;             
    SELECT MNEMONICO INTO EMPRESA FROM TP_EMPRESA WHERE ID_EMPRESA = IS_ID_EMPRESA;
    INSERT INTO TP_BLOQUEO VALUES(IS_USUARIO, EMPRESA, SYSDATE, IS_ESTADO, 0);
    COMMIT;  
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Usuario registrado correctamente.';
ELSE
  OS_COD_RETORNO := '10';
  OS_MEN_RETORNO := 'El usuario ya existe';
END IF;


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
      
 
END;

PROCEDURE SPU_ACTUALIZAR_USUARIO(
IS_ID_USUARIO IN NUMBER,
IS_ID_EMPRESA IN NUMBER,
IS_USUARIO IN VARCHAR2,
--IS_CONTRASENA IN VARCHAR2,
--IS_APELLIDOMATERNO IN VARCHAR2,
IS_APELLIDOPATERNO IN VARCHAR2,
IS_NOMBRE IN VARCHAR2,
IS_CORREO IN VARCHAR2,
IS_ESTADO IN VARCHAR,
IS_TIPODOCUMENTO IN VARCHAR2,
IS_NUMERODOCUMENTO IN VARCHAR2,
IS_TELEFONO IN VARCHAR2,
--IS_FECHACAMBIOCLAVE IN TIMESTAMP,
--IS_FECHALOGIN IN TIMESTAMP,
IS_MAC IN VARCHAR2,
IS_USUARIO_AGR     IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2

)
IS

BEGIN

 UPDATE TP_USUARIO SET
                USUARIO = IS_USUARIO,
                --CONTRASENA = IS_CONTRASENA,
                APELLIDOPATERNO = IS_APELLIDOPATERNO,
                --APELLIDOMATERNO = IS_APELLIDOMATERNO,
                NOMBRE = IS_NOMBRE,
                CORREO = IS_CORREO,
                ESTADO = IS_ESTADO,
                TIPODOCUMENTO = IS_TIPODOCUMENTO,
                NUMERODOCUMENTO = IS_NUMERODOCUMENTO,
                TELEFONO = IS_TELEFONO,
                --FECHA_CAMBIO_CLAVE = IS_FECHACAMBIOCLAVE,
                --FECHA_LOGIN = IS_FECHALOGIN,
                MAC = IS_MAC,
        AUD_FEC_MODIF = SYSDATE,
        AUD_USU_MODIF = IS_USUARIO_AGR 
                WHERE ID_USUARIO=IS_ID_USUARIO;             
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Usuario actualizado correctamente.';


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPU_ACTUALIZAR_DATOS(
IS_ID_USUARIO IN NUMBER,
IS_ID_EMPRESA IN NUMBER,
IS_USUARIO IN VARCHAR2,
IS_CONTRASENA IN VARCHAR2,
IS_APELLIDOMATERNO IN VARCHAR2,
IS_APELLIDOPATERNO IN VARCHAR2,
IS_NOMBRE IN VARCHAR2,
IS_CORREO IN VARCHAR2,
IS_ESTADO IN VARCHAR,
IS_TIPODOCUMENTO IN VARCHAR2,
IS_NUMERODOCUMENTO IN VARCHAR2,
IS_TELEFONO IN VARCHAR2,
IS_FECHACAMBIOCLAVE IN TIMESTAMP,
IS_FECHALOGIN IN TIMESTAMP,
IS_MAC IN VARCHAR2,
IS_FECHAMODIFICACION IN TIMESTAMP,
IS_USUARIOMODIFICACION IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2

)
IS

BEGIN

 UPDATE TP_USUARIO SET
                USUARIO = IS_USUARIO,
                CONTRASENA = IS_CONTRASENA,
                APELLIDOPATERNO = IS_APELLIDOPATERNO,
                --APELLIDOMATERNO = IS_APELLIDOMATERNO,
                NOMBRE = IS_NOMBRE,
                CORREO = IS_CORREO,
                ESTADO = IS_ESTADO,
                TIPODOCUMENTO = IS_TIPODOCUMENTO,
                NUMERODOCUMENTO = IS_NUMERODOCUMENTO,
                TELEFONO = IS_TELEFONO,
                FECHA_CAMBIO_CLAVE = IS_FECHACAMBIOCLAVE,
                --FECHA_LOGIN = IS_FECHALOGIN,
                MAC = IS_MAC,
                AUD_FEC_MODIF =IS_FECHAMODIFICACION  ,
                AUD_USU_MODIF= IS_USUARIOMODIFICACION  
                WHERE ID_USUARIO=IS_ID_USUARIO;             
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Usuario actualizado correctamente.';


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPD_ELIMINAR_USUARIO(
IS_ID_USUARIO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
)
IS

BEGIN

 DELETE TP_BLOQUEO WHERE USUARIO = (SELECT USUARIO FROM TP_USUARIO WHERE ID_USUARIO = IS_ID_USUARIO);
 DELETE TR_ROL_X_USUARIO WHERE ID_USUARIO = IS_ID_USUARIO;
 DELETE TP_USUARIO WHERE ID_USUARIO=IS_ID_USUARIO;             
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Usuario eliminado correctamente.';


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_USUARIO(
IS_COD_USUARIO        IN NUMBER,
IS_USUARIO            IN VARCHAR2,
OS_COD_RETORNO        OUT VARCHAR2,
OS_MEN_RETORNO        OUT VARCHAR2,
OS_CURSOR             OUT T_CURSOR
)
IS
V_CURSOR      T_CURSOR;
T_QUERY       VARCHAR2(1000);
BEGIN
   
  T_QUERY := ' SELECT e.ID_EMPRESA,e.MNEMONICO AS EMPRESA,ID_USUARIO,USUARIO,CONTRASENA,u.NOMBRE,APELLIDOPATERNO, ' ||
             ' APELLIDOMATERNO,CORREO,u.ESTADO,TIPODOCUMENTO,NUMERODOCUMENTO,TELEFONO,' ||
             ' FECHA_CAMBIO_CLAVE,FECHA_LOGIN,MAC ' ||
             ' FROM TP_USUARIO u LEFT JOIN TP_EMPRESA e ON u.ID_EMPRESA=e.ID_EMPRESA ' ||
             ' WHERE 1=1';
             
   IF IS_COD_USUARIO != -1 THEN
     T_QUERY := T_QUERY || ' AND ID_USUARIO=' || IS_COD_USUARIO;
   END IF;
 
   IF IS_USUARIO IS NOT NULL THEN
     T_QUERY := T_QUERY || ' AND USUARIO LIKE ''' || IS_USUARIO || '%''';
   END IF;
      
   OPEN OS_CURSOR FOR T_QUERY;
      
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;



PROCEDURE SPS_CONSULTAR_USUARIO_LOGIN(
IS_USUARIO            IN VARCHAR2,
OS_COD_RETORNO        OUT VARCHAR2,
OS_MEN_RETORNO        OUT VARCHAR2,
OS_CURSOR             OUT T_CURSOR
)
IS
V_CURSOR      T_CURSOR;
T_QUERY       VARCHAR2(1000);
BEGIN
    OPEN V_CURSOR FOR
    SELECT u.ID_EMPRESA,e.MNEMONICO AS EMPRESA,ID_USUARIO,USUARIO,CONTRASENA,u.NOMBRE,APELLIDOPATERNO, 
             APELLIDOMATERNO,CORREO,u.ESTADO,TIPODOCUMENTO,NUMERODOCUMENTO,TELEFONO,
             NVL(TO_CHAR(FECHA_CAMBIO_CLAVE,'YYYY-MM-DD HH24:MI:SS'),' ') AS FECHA_CAMBIO_CLAVE,   
             NVL(TO_CHAR(FECHA_LOGIN,'YYYY-MM-DD HH24:MI:SS'),' ') AS FECHA_LOGIN,   
             NVL(TO_CHAR(u.AUD_FEC_CREAC,'YYYY-MM-DD HH24:MI:SS'),' ') AS AUD_FEC_CREAC, MAC 
             FROM TP_USUARIO u LEFT JOIN TP_EMPRESA e ON u.ID_EMPRESA=e.ID_EMPRESA 
             WHERE 1=1 AND USUARIO = IS_USUARIO ;
      
   OS_CURSOR:=  V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_USUARIO_TODOS(
IS_ID_EMPRESA          IN NUMBER,
IS_NOMBRE              IN VARCHAR2,
IS_APELLIDO            IN VARCHAR2,
IS_ESTADO              IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
) 

IS
T_QUERY VARCHAR2(1500);

BEGIN
   T_QUERY := 'SELECT U.ID_USUARIO, U.USUARIO, U.NOMBRE, U.APELLIDOPATERNO, U.ESTADO, U.TIPODOCUMENTO, U.NUMERODOCUMENTO, EM.NOMBRE AS EMPRESA ' ||
              'FROM TP_USUARIO U INNER JOIN TP_EMPRESA EM ON U.ID_EMPRESA=EM.ID_EMPRESA WHERE 1=1';
   
   IF IS_ID_EMPRESA > 0 THEN
    T_QUERY:= T_QUERY || ' AND U.ID_EMPRESA = ' || IS_ID_EMPRESA;
   END IF;
   
   IF TRIM(IS_NOMBRE) IS NOT NULL THEN
    T_QUERY:= T_QUERY || ' AND U.NOMBRE LIKE ''' || IS_NOMBRE || '%''';
   END IF;
   
   IF TRIM(IS_APELLIDO) IS NOT NULL THEN
    T_QUERY:= T_QUERY || ' AND U.APELLIDOPATERNO LIKE ''' || IS_APELLIDO || '%''';
   END IF;
   
   IF (TRIM(IS_ESTADO) IS NOT NULL) AND (IS_ESTADO <> '-1') THEN
    T_QUERY:= T_QUERY || ' AND U.ESTADO = ''' || IS_ESTADO || '''';
   END IF;
              
   OPEN OS_CURSOR FOR T_QUERY;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_CONSULTAR_ROL_POR_USUARIO(
IS_USUARIO          IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;
T_QUERY  VARCHAR2(500);

BEGIN
   OPEN V_CURSOR FOR SELECT R.ID_ROL AS CODIGO,R.MNEMONICO AS NOMBRE ,R.ESTADO
          FROM TP_ROL R
          WHERE R.ID_ROL IN (SELECT RU.ID_ROL FROM TR_ROL_X_USUARIO RU WHERE RU.ID_USUARIO=IS_USUARIO );
      

   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_PERM_POR_USUARIO(
IS_USUARIO          IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;
T_QUERY  VARCHAR2(300);

BEGIN
   OPEN V_CURSOR FOR SELECT P.MNEMONICO,P.ID_PERMISO
              FROM TP_PERMISO P
              WHERE P.ID_PERMISO IN 
              (SELECT PR.ID_PERMISO FROM TR_PERMISO_X_ROL PR
              WHERE PR.ID_ROL IN (SELECT RU.ID_ROL FROM TR_ROL_X_USUARIO RU WHERE RU.ID_USUARIO=IS_USUARIO ) );
      

   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;



PROCEDURE SPS_VERI_SUPER_USUARIO(
IS_USUARIO        IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;
T_QUERY  VARCHAR2(300);

BEGIN
   OPEN V_CURSOR FOR 
   SELECT U.ID_EMPRESA, (SELECT E.MNEMONICO FROM TP_EMPRESA E WHERE E.ID_EMPRESA = U.ID_EMPRESA) MNEMONICO--, 
    FROM TP_USUARIO U 
    WHERE U.ID_USUARIO=IS_USUARIO;

   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;



PROCEDURE SPS_CONSULTAR_USU_DES_BLO(
  IS_ID_EMPRESA          IN VARCHAR2,
  IS_NOMBRE              IN VARCHAR2, 
  IS_ESTADO              IN VARCHAR2,
  OS_COD_RETORNO         OUT VARCHAR2,
  OS_MEN_RETORNO         OUT VARCHAR2,
  OS_CURSOR              OUT T_CURSOR
)
IS
  T_QUERY VARCHAR2(1000);
BEGIN

  T_QUERY := 'SELECT U.ID_USUARIO, U.NOMBRE, U.APELLIDOPATERNO AS APELLIDO, U.TIPODOCUMENTO || '' '' || U.NUMERODOCUMENTO AS DOCUMENTO, U.USUARIO, E.NOMBRE AS EMPRESA
              FROM TP_USUARIO U INNER JOIN TP_EMPRESA E ON U.ID_EMPRESA = E.ID_EMPRESA WHERE 1=1';
  
  IF IS_ESTADO = 'BLOQUEADO' THEN
    T_QUERY := T_QUERY || ' AND U.ESTADO <> ''' || IS_ESTADO || '''';
  ELSIF IS_ESTADO = 'HABILITADO' THEN
    T_QUERY := T_QUERY || ' AND U.ESTADO = ''BLOQUEADO''';
  END IF;
  
  IF IS_ID_EMPRESA <> '-1' THEN
    T_QUERY := T_QUERY || ' AND E.ID_EMPRESA = ' || IS_ID_EMPRESA;
  END IF;
  
  IF IS_NOMBRE IS NOT NULL THEN
    T_QUERY := T_QUERY || ' AND U.NOMBRE LIKE ''' || IS_NOMBRE || '%''';
  END IF;

  OPEN OS_CURSOR FOR T_QUERY;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPU_REGISTRAR_USU_DES_BLO(
  IS_USUARIOS          IN VARCHAR2,
  IS_USUARIO       IN VARCHAR2,
  IS_ESTADO              IN VARCHAR2,
  OS_COD_RETORNO         OUT VARCHAR2,
  OS_MEN_RETORNO         OUT VARCHAR2,
  OS_CURSOR              OUT T_CURSOR
)
IS
  T_QUERY VARCHAR2(1000);
  T_USUARIO NUMBER;
  COND_MIN  NUMBER;
  COND_MAX  NUMBER;
  ITERA     NUMBER; 
BEGIN 
  COND_MIN  := 1;
  COND_MAX  := 1;
  ITERA     := 1;  
  LOOP
    T_USUARIO := TO_NUMBER(GET_TOKEN(IS_USUARIOS, ITERA));
    ITERA := ITERA + 1;
    IF T_USUARIO IS NOT NULL THEN 
      UPDATE TP_USUARIO SET ESTADO = IS_ESTADO, AUD_FEC_MODIF = SYSDATE, AUD_USU_MODIF = IS_USUARIO WHERE ID_USUARIO = T_USUARIO;
    END IF;
    
    EXIT WHEN T_USUARIO IS NULL;
  END LOOP;
  COMMIT;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;



/*
==========================
STORE PROCEDURE DE APLICACION
===========================*/

PROCEDURE SPS_CONSULTAR_APLICACIONES_USU(
  IS_ID_EMPRESA IN VARCHAR2,
  OS_COD_RETORNO         OUT VARCHAR2,
  OS_MEN_RETORNO         OUT VARCHAR2,
  OS_CURSOR               OUT T_CURSOR
)
IS
BEGIN
  
  IF IS_ID_EMPRESA <> '-1' THEN 
    OPEN OS_CURSOR FOR SELECT ID_APLICACION AS CODIGO, NOMBRE FROM TP_APLICACION WHERE ID_EMPRESA = TO_NUMBER(IS_ID_EMPRESA);
  END IF;
    
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Empresa registrada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
  
END;

PROCEDURE SPS_CONSULTAR_APLICACION_DATA(
  IS_TIPO IN NUMBER,
  OS_COD_RETORNO         OUT VARCHAR2,
  OS_MEN_RETORNO         OUT VARCHAR2,
  OS_CURSOR               OUT T_CURSOR
)
IS
BEGIN
  IF IS_TIPO = 1 THEN
     OPEN OS_CURSOR FOR SELECT ID_APLICACION AS CODIGO, NOMBRE FROM TP_APLICACION;
  ELSE
    OPEN OS_CURSOR FOR SELECT MNEMONICO AS CODIGO, NOMBRE FROM TP_APLICACION;
  END IF;
  
 
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Empresa registrada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
  
END;

PROCEDURE SPI_REGISTRAR_APLICACION(
IS_ID_EMPRESA IN NUMBER,
IS_MNEMONICO IN VARCHAR2,
IS_NOMBRE IN VARCHAR2,
IS_DESCRIPCION IN VARCHAR2,
IS_ESTADO IN VARCHAR2,
IS_POLITICA IN VARCHAR2,
IS_USUARIO  IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_COD_ID_APLICACION     OUT NUMBER
)
IS
 CONT NUMBER;
BEGIN
  
  SELECT COUNT(1) INTO CONT FROM TP_APLICACION WHERE MNEMONICO = IS_MNEMONICO AND ID_EMPRESA = IS_ID_EMPRESA;

IF CONT = 0 THEN
 INSERT INTO TP_APLICACION(
                ID_EMPRESA,
                ID_APLICACION,
                MNEMONICO,
                NOMBRE,
                DESCRIPCION,
                ESTADO,
                POLITICA_ACTIVA,
        AUD_FEC_CREAC,
        AUD_USU_CREAC
                )
            VALUES(
                IS_ID_EMPRESA,
                SEQ_APLICACION.NEXTVAL,
                IS_MNEMONICO,
                IS_NOMBRE,
                IS_DESCRIPCION,
                IS_ESTADO, '0',
        SYSDATE, IS_USUARIO) RETURNING ID_APLICACION INTO OS_COD_ID_APLICACION;             
                
  INSERT INTO TS_ATRIBUTO_APLICACION (SELECT ID_POLITICA, ID_ATRIBUTO, IS_MNEMONICO, VALOR, IS_ID_EMPRESA FROM TS_ATRIBUTO_EMPRESA
                                      WHERE EMPRESA = (SELECT MNEMONICO FROM TP_EMPRESA WHERE ID_EMPRESA = IS_ID_EMPRESA));
                
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Aplicacion registrada correctamente.';
ELSE
  OS_COD_RETORNO := '10';
  OS_MEN_RETORNO := 'La Aplicacion ya existe';
END IF;

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
      
 
END;

PROCEDURE SPU_ACTIVAR_POLITICA(
IS_ID_APLICACION   IN NUMBER,
IS_ESTADO       IN VARCHAR2,
IS_USUARIO       IN VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2
)
IS

BEGIN 
  UPDATE TP_APLICACION SET POLITICA_ACTIVA = IS_ESTADO, AUD_FEC_MODIF = SYSDATE, AUD_USU_MODIF = IS_USUARIO WHERE ID_APLICACION = IS_ID_APLICACION;             
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Aplicación actualizada correctamente.';


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;
 

PROCEDURE SPU_ACTUALIZAR_APLICACION(
IS_ID_APLICACION   IN NUMBER,
IS_NOMBRE       IN VARCHAR2,
IS_DESCRIPCION     IN VARCHAR2,
IS_ESTADO       IN VARCHAR,
IS_POLITICA     IN VARCHAR,
IS_USUARIO       IN VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2
)
IS

BEGIN

 UPDATE TP_APLICACION SET NOMBRE = IS_NOMBRE,
                          DESCRIPCION = IS_DESCRIPCION,
                          ESTADO = ESTADO,  
                          AUD_FEC_MODIF = SYSDATE, AUD_USU_MODIF = IS_USUARIO WHERE ID_APLICACION=IS_ID_APLICACION;             
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Aplicación actualizada correctamente.';


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPD_ELIMINAR_APLICACION(
IS_ID_APLICACION IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2

)
IS
  IS_EMPRESA NUMBER;
  EX_NO_DELETE exception;
  pragma exception_init (EX_NO_DELETE,-02292);
BEGIN
  SELECT ID_EMPRESA INTO IS_EMPRESA FROM TP_APLICACION WHERE ID_APLICACION = IS_ID_APLICACION;
  DELETE TS_ATRIBUTO_APLICACION WHERE ID_EMPRESA = IS_EMPRESA AND APLICACION = (SELECT MNEMONICO FROM TP_APLICACION WHERE ID_APLICACION = IS_ID_APLICACION);
  DELETE TP_APLICACION WHERE ID_APLICACION=IS_ID_APLICACION;    

  COMMIT;
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Aplicación eliminada correctamente.';


 EXCEPTION
    WHEN EX_NO_DELETE THEN
    OS_COD_RETORNO := '30';
    OS_MEN_RETORNO := 'La aplicacinull;n no puede ser eliminada, porque se encuentra asociada a un Rol y/o Permiso';
 
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_APP_EMP(
IS_APLICACION        IN VARCHAR2,
IS_EMPRESA    IN VARCHAR2,
OS_COD_RETORNO          OUT VARCHAR2,
OS_MEN_RETORNO          OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;
 
BEGIN
    
  OPEN V_CURSOR FOR 
  SELECT ap.ID_EMPRESA,ap.ID_APLICACION,ap.MNEMONICO,ap.NOMBRE,ap.DESCRIPCION,ap.ESTADO FROM TP_APLICACION ap INNER JOIN TP_EMPRESA e
  ON ap.ID_EMPRESA= e.ID_EMPRESA 
  WHERE  ap.MNEMONICO = IS_APLICACION 
  AND e.MNEMONICO = IS_EMPRESA;
  
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_CONSULTAR_APLICACION(
IS_ID_APLICACION        IN NUMBER,
OS_COD_RETORNO          OUT VARCHAR2,
OS_MEN_RETORNO          OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
V_CURSOR T_CURSOR;
 
BEGIN
   T_QUERY := ' SELECT AP.ID_APLICACION, AP.MNEMONICO, AP.NOMBRE, AP.DESCRIPCION, AP.ESTADO,  EM.ID_EMPRESA, EM.NOMBRE AS EMPRESA, AP.POLITICA_ACTIVA' ||
              ' FROM TP_APLICACION AP INNER JOIN TP_EMPRESA EM ON AP.ID_EMPRESA = EM.ID_EMPRESA ' ||
              ' WHERE AP.ID_APLICACION ='|| IS_ID_APLICACION;
   
   OPEN OS_CURSOR FOR T_QUERY;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_APLICACION_TODAS(
IS_ID_EMPRESA          IN NUMBER,
IS_NOMBRE              IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);

BEGIN
  
   T_QUERY := 'SELECT AP.ID_APLICACION, AP.MNEMONICO, AP.NOMBRE, AP.DESCRIPCION, AP.ESTADO, EM.NOMBRE AS EMPRESA, AP.POLITICA_ACTIVA ' ||
              'FROM TP_APLICACION AP INNER JOIN TP_EMPRESA EM ON AP.ID_EMPRESA = EM.ID_EMPRESA WHERE 1=1';

   IF IS_ID_EMPRESA > -1 THEN
      T_QUERY := T_QUERY || ' AND AP.ID_EMPRESA='||IS_ID_EMPRESA;             
   END IF;
  
   IF IS_NOMBRE IS NOT NULL THEN
      T_QUERY := T_QUERY || ' AND AP.NOMBRE LIKE ''' || IS_NOMBRE || '%''';             
   END IF;
   
   OPEN OS_CURSOR FOR T_QUERY;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;



PROCEDURE SPS_REG_ROLES_USER_APP(
IS_ROLES               IN VARCHAR2,
IS_APLICACION          IN NUMBER,
IS_USUARIO             IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2
)
IS
ITERA        NUMBER;
COND_MAX     NUMBER;
COND_MIN     NUMBER;
T_ROL        VARCHAR2(50);
BEGIN
  DELETE TR_ROL_X_USUARIO WHERE ID_ROL IN (SELECT RO.ID_ROL FROM TP_ROL RO 
                                           INNER JOIN TP_APLICACION APP ON RO.ID_APLICACION = APP.ID_APLICACION 
                                           INNER JOIN TR_ROL_X_USUARIO RU ON RU.ID_ROL = RO.ID_ROL
                                           WHERE APP.ID_APLICACION = IS_APLICACION AND RU.ID_USUARIO=IS_USUARIO);
  COND_MIN  := 1;
  COND_MAX  := 1;
  ITERA     := 1;  
  LOOP
    T_ROL := GET_TOKEN(IS_ROLES, ITERA);
    ITERA := ITERA + 1;
    IF T_ROL IS NOT NULL THEN 
      INSERT INTO TR_ROL_X_USUARIO VALUES (IS_USUARIO, T_ROL);
    END IF;
    
    EXIT WHEN T_ROL IS NULL;
  END LOOP;
  COMMIT;
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;


PROCEDURE SPS_CONSULTAR_APLICACION_EMP(
  IS_ID_EMPRESA           IN VARCHAR2,
  OS_COD_RETORNO          OUT VARCHAR2,
  OS_MEN_RETORNO          OUT VARCHAR2,
  OS_CURSOR               OUT T_CURSOR
)
IS
BEGIN
  OPEN OS_CURSOR FOR SELECT ID_APLICACION AS CODIGO, NOMBRE FROM TP_APLICACION WHERE ID_EMPRESA = IS_ID_EMPRESA ;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Empresa registrada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
  
END;


PROCEDURE SPS_CONSULTAR_PICKDATA_ROLES(
IS_APLICACION          IN NUMBER,
IS_USUARIO             IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;
T_QUERY  VARCHAR2(300);
BEGIN
   
           OPEN V_CURSOR FOR SELECT RO.ID_ROL AS CODIGO, RO.NOMBRE AS ROL, 'FALSE' AS SELECCION FROM TP_ROL RO
                     INNER JOIN TP_APLICACION AP ON RO.ID_APLICACION = AP.ID_APLICACION 
                     WHERE AP.ID_APLICACION = IS_APLICACION AND RO.ID_ROL NOT IN ( 
                                                  SELECT RO.ID_ROL FROM TP_ROL RO 
                                                  INNER JOIN TP_APLICACION APP ON RO.ID_APLICACION = APP.ID_APLICACION 
                                                  INNER JOIN TR_ROL_X_USUARIO RU ON RU.ID_ROL = RO.ID_ROL
                                                  WHERE APP.ID_APLICACION = IS_APLICACION AND RU.ID_USUARIO=IS_USUARIO)
                      UNION 
                      SELECT RO.ID_ROL AS CODIGO, RO.NOMBRE AS ROL, 'TRUE' AS SELECCION FROM TP_ROL RO 
                      INNER JOIN TP_APLICACION APP ON RO.ID_APLICACION = APP.ID_APLICACION 
                      INNER JOIN TR_ROL_X_USUARIO RU ON RU.ID_ROL = RO.ID_ROL
                      WHERE APP.ID_APLICACION = IS_APLICACION AND RU.ID_USUARIO = IS_USUARIO;
                     
                             
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_REG_PERM_ROL_APP(
IS_PERMISOS               IN VARCHAR2,
IS_ROL             IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2
)
IS
ITERA        NUMBER;
COND_MAX     NUMBER;
COND_MIN     NUMBER;
T_PERMISO        VARCHAR2(50);
BEGIN
  DELETE FROM TR_PERMISO_X_ROL WHERE ID_ROL = IS_ROL;
  COND_MIN  := 1;
  COND_MAX  := 1;
  ITERA     := 1;  
  LOOP
    T_PERMISO := GET_TOKEN(IS_PERMISOS, ITERA);
    ITERA := ITERA + 1;
    IF T_PERMISO IS NOT NULL THEN 
      INSERT INTO TR_PERMISO_X_ROL VALUES (IS_ROL, T_PERMISO);
    END IF;
    
    EXIT WHEN T_PERMISO IS NULL;
  END LOOP;
  COMMIT;
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;



PROCEDURE SPS_REG_ROL_X_ROL_APP(
IS_ROLES               IN VARCHAR2,
IS_ROL             IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2
)
IS
ITERA        NUMBER;
COND_MAX     NUMBER;
COND_MIN     NUMBER;
T_ROL        VARCHAR2(50);
BEGIN
  DELETE FROM TR_ROLES_X_ROL WHERE ID_ROL = IS_ROL;
  COND_MIN  := 1;
  COND_MAX  := 1;
  ITERA     := 1;  
  LOOP
    T_ROL := GET_TOKEN(IS_ROLES, ITERA);
    ITERA := ITERA + 1;
    IF T_ROL IS NOT NULL THEN 
      INSERT INTO TR_ROLES_X_ROL VALUES (T_ROL,IS_ROL);
    END IF;
    
    EXIT WHEN T_ROL IS NULL;
  END LOOP;
  COMMIT;
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;


/*
==========================
STORE PROCEDURE DE ROL
===========================*/

PROCEDURE SPI_REGISTRAR_ROL(
IS_ID_APLICACION NUMBER,
IS_MNEMONICO   IN VARCHAR2,
IS_NOMBRE     IN VARCHAR2,
IS_DESCRIPCION   IN VARCHAR2,
IS_ESTADO     IN VARCHAR2,
IS_USUARIO     IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_COD_ROL          OUT NUMBER,
OS_EMPRESA          OUT VARCHAR2


)
IS
CONTADOR NUMBER := 0;

BEGIN
  
   SELECT COUNT(*) INTO CONTADOR FROM TP_ROL 
          WHERE MNEMONICO = IS_MNEMONICO
          AND ID_APLICACION = IS_ID_APLICACION;
   
   IF CONTADOR = 0 THEN 
   SELECT SEQ_ROL.NEXTVAL INTO OS_COD_ROL FROM DUAL;
   
     INSERT INTO TP_ROL(
                  ID_APLICACION,
                  ID_ROL,
                  MNEMONICO,
                  NOMBRE,
                  DESCRIPCION,
                  ESTADO,
          AUD_FEC_CREAC,
          AUD_USU_CREAC
                  )
              VALUES(
                  IS_ID_APLICACION,
                  OS_COD_ROL,

                  IS_MNEMONICO,
                  IS_NOMBRE,
                  IS_DESCRIPCION,
                  IS_ESTADO,
          SYSDATE,
          IS_USUARIO
          );
          
                        

      COMMIT;
      
      OS_EMPRESA:=FUN_EMPRESA_X_APLICACION(IS_ID_APLICACION);
      OS_COD_RETORNO := '00';
      OS_MEN_RETORNO := 'Rol registrado correctamente.';
   
      ELSE 
      OS_COD_RETORNO := '10';
      OS_MEN_RETORNO := 'El codigo de rol ya existe.';
   END IF;



 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
      
 
END;

PROCEDURE SPU_ACTUALIZAR_ROL(
IS_ID_ROL       IN NUMBER,
IS_NOMBRE       IN VARCHAR2,
IS_MNEMONICO     IN VARCHAR2,
IS_DESCRIPCION     IN VARCHAR2,
IS_ESTADO       IN VARCHAR2,
IS_USUARIO      IN VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2,
OS_EMPRESA      OUT VARCHAR2
)
IS
CONTADOR NUMBER := 0;
BEGIN
  
         UPDATE TP_ROL SET
                    NOMBRE = IS_NOMBRE,
                    DESCRIPCION = IS_DESCRIPCION,        
                    ESTADO = IS_ESTADO, 
          AUD_FEC_MODIF = SYSDATE,
          AUD_USU_MODIF = IS_USUARIO 
          WHERE ID_ROL= IS_ID_ROL;  
                             
        COMMIT;
         OS_MEN_RETORNO := 'Rol ha actualizado correctamente.';
         OS_COD_RETORNO := '00';
      
 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPD_ELIMINAR_ROL(
IS_ID_ROL IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
)
IS
ROL_ASOC NUMBER;

BEGIN
  SELECT COUNT(*) INTO ROL_ASOC
  FROM (SELECT 'FALSE' AS ROL_ELI FROM TR_ROLES_X_ROL TR
    WHERE TR.ID_ROL_PADRE = IS_ID_ROL OR
    TR.ID_ROL = IS_ID_ROL
  UNION ALL  
  SELECT 'FALSE' AS ROL_ELI FROM TR_ROL_X_USUARIO TU
    WHERE TU.ID_ROL = IS_ID_ROL);

IF ROL_ASOC = 0 THEN
   DELETE TP_ROL WHERE ID_ROL= IS_ID_ROL;             
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Rol eliminado correctamente.';
ELSE
    OS_COD_RETORNO := '30';
    OS_MEN_RETORNO := 'El rol no puede ser eliminado porque se encuentra asociado a otro rol o a un usuario';
END IF;


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_ROL(
IS_ROL IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
V_CURSOR T_CURSOR;

BEGIN

   T_QUERY := ' SELECT R.ID_ROL,R.MNEMONICO, R.NOMBRE NOMBRE, 
                R.DESCRIPCION, R.ESTADO, AP.ID_APLICACION, E.ID_EMPRESA
                FROM TP_ROL R JOIN TP_APLICACION AP ON R.ID_APLICACION = AP.ID_APLICACION
                JOIN TP_EMPRESA E ON E.ID_EMPRESA = AP.ID_EMPRESA
                WHERE R.ID_ROL =  '||IS_ROL; 
                
   OPEN V_CURSOR FOR T_QUERY;
   OS_CURSOR := V_CURSOR;
   
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_ROL_TODAS(
IS_ROL IN VARCHAR2,
IS_ID_EMPRESA IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
V_CURSOR T_CURSOR;
T_CONCAT_WHERE VARCHAR(300);


BEGIN
  IF IS_ROL IS NOT NULL THEN
      T_CONCAT_WHERE := ' AND UPPER(R.NOMBRE) LIKE UPPER(''%'|| IS_ROL||'%'')';
   END IF;
   
   IF IS_ID_APLICACION IS NOT NULL THEN
      T_CONCAT_WHERE := T_CONCAT_WHERE||' AND R.ID_APLICACION='||IS_ID_APLICACION;
   END IF;
   
   IF IS_ID_EMPRESA IS NOT NULL THEN
      T_CONCAT_WHERE := T_CONCAT_WHERE|| ' AND AP.ID_APLICACION IN (SELECT A.ID_APLICACION FROM TP_APLICACION A WHERE A.ID_EMPRESA = '||IS_ID_EMPRESA||') ';
   END IF;
   T_QUERY := ' SELECT R.ID_ROL,R.MNEMONICO, R.NOMBRE R_NOMBRE, 
                R.DESCRIPCION, R.ESTADO, AP.ID_APLICACION, AP.NOMBRE A_NOMBRE, E.ID_EMPRESA, E.NOMBRE E_NOMBRE
                FROM TP_ROL R JOIN TP_APLICACION AP ON R.ID_APLICACION = AP.ID_APLICACION
                JOIN TP_EMPRESA E ON E.ID_EMPRESA = AP.ID_EMPRESA
                WHERE 1=1 '||T_CONCAT_WHERE; 
                
    
   OPEN V_CURSOR FOR T_QUERY;
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';
    ROLLBACK;

 EXCEPTION
    WHEN OTHERS THEN
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_ROLES(
IS_USUARIO IN VARCHAR2,
IS_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   
   OPEN V_CURSOR FOR
     SELECT p.MNEMONICO AS ROL FROM TP_APLICACION ap, TP_ROL p, TR_ROL_X_USUARIO ru, TP_USUARIO u
   WHERE ap.ID_APLICACION=p.ID_APLICACION
   AND p.ID_ROL=ru.ID_ROL
   AND ru.ID_USUARIO=u.ID_USUARIO
   AND u.USUARIO=IS_USUARIO
   AND ap.MNEMONICO=IS_APLICACION;
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_ROL_APLI_DATA(
IS_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   
   OPEN V_CURSOR FOR
   SELECT ID_ROL AS CODIGO, NOMBRE
   FROM TP_ROL
   WHERE ID_APLICACION =IS_APLICACION;
  
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_ROL_DATA(
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   
   OPEN V_CURSOR FOR
   SELECT ID_ROL AS CODIGO, NOMBRE
   FROM TP_ROL;
   
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_CONSULTAR_PERMISO_DATA(
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   
   OPEN V_CURSOR FOR
   SELECT ID_PERMISO AS CODIGO, NOMBRE
   FROM TP_PERMISO;
   
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_ROL_PADRES(
IS_ROL IN NUMBER,
IS_APLICACION IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   
   OPEN V_CURSOR FOR
   SELECT R.ID_ROL AS CODIGO, R.NOMBRE, 'TRUE' SELECCION
    FROM TP_ROL R 
    WHERE R.ID_ROL IN (SELECT RR.ID_ROL_PADRE FROM TR_ROLES_X_ROL RR WHERE RR.ID_ROL = IS_ROL )
    AND ID_APLICACION = IS_APLICACION
    UNION
    SELECT R.ID_ROL AS CODIGO, R.NOMBRE, 'FALSE' SELECCION
    FROM TP_ROL R 
    WHERE R.ID_ROL NOT IN (SELECT RR.ID_ROL_PADRE FROM TR_ROLES_X_ROL RR WHERE RR.ID_ROL = IS_ROL )
    AND R.ID_ROL NOT IN (SELECT RR.ID_ROL FROM TR_ROLES_X_ROL RR WHERE RR.ID_ROL_PADRE = IS_ROL)
    AND R.ID_ROL <> IS_ROL
    AND ID_APLICACION = IS_APLICACION;

   
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;



/*
==========================
STORE PROCEDURE DE PERMISO
===========================*/

PROCEDURE SPI_REGISTRAR_PERMISO(
IS_ID_APLICACION   NUMBER,
IS_MNEMONICO     IN VARCHAR2,
IS_NOMBRE       IN VARCHAR2,
IS_DESCRIPCION     IN VARCHAR2,
IS_ESTADO       IN VARCHAR2,
IS_TIPO       IN VARCHAR2,
IS_USUARIO       IN VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2,
OS_COD_ID_PERMISO   OUT NUMBER
)
IS
CONT NUMBER;
BEGIN

SELECT COUNT(1) INTO CONT FROM TP_PERMISO WHERE MNEMONICO = IS_MNEMONICO AND ID_APLICACION = IS_ID_APLICACION;
 
IF CONT = 0 THEN 
 
 INSERT INTO TP_PERMISO(
                ID_APLICACION,
                ID_PERMISO,
                MNEMONICO,
                NOMBRE,
                DESCRIPCION,
                ESTADO,
                TIPO,
        AUD_FEC_CREAC,
        AUD_USU_CREAC
                )
            VALUES(
                IS_ID_APLICACION,
                SEQ_PERMISO.NEXTVAL,
                IS_MNEMONICO,
                IS_NOMBRE,    
                IS_DESCRIPCION,
                IS_ESTADO,
                IS_TIPO,
        SYSDATE,
        IS_USUARIO) RETURNING ID_PERMISO INTO OS_COD_ID_PERMISO;
                
    COMMIT;                        
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Permiso registrado correctamente';

ELSE
  OS_COD_RETORNO := '10';
  OS_MEN_RETORNO := 'El Permiso ya existe';
END IF;


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;     
 
END;

PROCEDURE SPU_ACTUALIZAR_PERMISO(
IS_ID_PERMISO     IN NUMBER,
IS_NOMBRE       IN VARCHAR2,
IS_MNEMONICO     IN VARCHAR2,
IS_DESCRIPCION     IN VARCHAR2,
IS_ESTADO       IN VARCHAR2,
IS_TIPO       IN VARCHAR2,
IS_USUARIO       IN VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2
)
IS
CONTADOR NUMBER := 0;
BEGIN

    SELECT COUNT(*) INTO CONTADOR
    FROM TP_PERMISO WHERE MNEMONICO = IS_MNEMONICO;

    IF CONTADOR = 1 THEN 
 UPDATE TP_PERMISO SET
                NOMBRE = IS_NOMBRE,
                DESCRIPCION = IS_DESCRIPCION,
                TIPO=IS_TIPO,
                ESTADO = IS_ESTADO,
        AUD_FEC_MODIF = SYSDATE,
        AUD_USU_MODIF = IS_USUARIO 
        WHERE ID_PERMISO= IS_ID_PERMISO ;             
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Permiso actualizado correctamente.';

ELSE 
        OS_MEN_RETORNO := 'El codigo de rol ya existe.';
        OS_COD_RETORNO := '10';
        
END IF;
  
  EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPD_ELIMINAR_PERMISO(
IS_ID_PERMISO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2

)
IS

BEGIN

 DELETE TP_PERMISO WHERE ID_PERMISO= IS_ID_PERMISO;             
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Rol eliminado correctamente.';


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_PERMISO(
IS_PERMISO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
V_CURSOR T_CURSOR;

BEGIN
    T_QUERY := 'SELECT P.ID_PERMISO,P.MNEMONICO,P.NOMBRE AS P_NOMBRE,
        P.DESCRIPCION,P.ESTADO,P.TIPO, AP.ID_APLICACION, AP.NOMBRE A_NOMBRE,
        E.ID_EMPRESA, E.NOMBRE E_NOMBRE
        FROM TP_PERMISO P
        LEFT JOIN TP_APLICACION AP ON P.ID_APLICACION= AP.ID_APLICACION
        LEFT JOIN TP_EMPRESA E ON   AP.ID_EMPRESA= E.ID_EMPRESA
        WHERE P.ID_PERMISO = '||IS_PERMISO; 

        
   OPEN V_CURSOR FOR T_QUERY;
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_CONSULTAR_PERM_TODAS(
IS_PERMISO IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
IS_ID_EMPRESA IN VARCHAR2,
IS_TIPO_PERMISO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
V_CURSOR T_CURSOR;
T_CONCAT_WHERE VARCHAR(300);

BEGIN

   IF TRIM(IS_PERMISO) IS NOT NULL THEN
      T_CONCAT_WHERE := ' AND UPPER(P.NOMBRE) LIKE UPPER(''%'|| IS_PERMISO||'%'')';
   END IF;
   
   IF (TRIM(IS_ID_APLICACION) IS NOT NULL) AND (IS_ID_APLICACION <> '-1')  THEN
      T_CONCAT_WHERE := T_CONCAT_WHERE||' AND AP.ID_APLICACION ='|| TO_NUMBER(IS_ID_APLICACION);
   END IF;
   
   IF (TRIM(IS_ID_EMPRESA) IS NOT NULL) AND (IS_ID_EMPRESA <> '-1')  THEN
      T_CONCAT_WHERE := T_CONCAT_WHERE||' AND E.ID_EMPRESA ='|| TO_NUMBER(IS_ID_EMPRESA);
   END IF;

   IF TRIM(IS_TIPO_PERMISO) IS NOT NULL THEN
      T_CONCAT_WHERE := T_CONCAT_WHERE || ' AND P.TIPO = '''|| IS_TIPO_PERMISO||'''';
   END IF;
   
   T_QUERY := 'SELECT P.ID_PERMISO,P.MNEMONICO,P.NOMBRE AS P_NOMBRE,
        P.DESCRIPCION,P.ESTADO,P.TIPO, AP.ID_APLICACION, AP.NOMBRE A_NOMBRE,
        E.ID_EMPRESA, E.NOMBRE E_NOMBRE
        FROM TP_PERMISO P
        INNER JOIN TP_APLICACION AP ON P.ID_APLICACION= AP.ID_APLICACION
        INNER JOIN TP_EMPRESA E ON   AP.ID_EMPRESA= E.ID_EMPRESA
        WHERE 1=1 '||T_CONCAT_WHERE;             
   OPEN V_CURSOR FOR T_QUERY;
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_CONSULTAR_PERMISO_TODAS(
IS_PERMISO IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
V_CURSOR T_CURSOR;
T_CONCAT_WHERE VARCHAR(300);

BEGIN

   IF IS_PERMISO IS NOT NULL THEN
      T_CONCAT_WHERE := ' AND P.MNEMONICO LIKE ''%'|| IS_PERMISO||'%''';
   END IF;
   
   IF IS_ID_APLICACION IS NOT NULL THEN
      T_CONCAT_WHERE := T_CONCAT_WHERE||' AND P.ID_APLICACION='||IS_ID_APLICACION;
   END IF;


   T_QUERY := 'SELECT P.ID_PERMISO,P.MNEMONICO,P.NOMBRE AS P_NOMBRE,
        P.DESCRIPCION,P.ESTADO,P.TIPO, AP.ID_APLICACION, AP.NOMBRE A_NOMBRE,
        E.ID_EMPRESA, E.NOMBRE E_NOMBRE
        FROM TP_PERMISO P
        INNER JOIN TP_APLICACION AP ON P.ID_APLICACION= AP.ID_APLICACION
        INNER JOIN TP_EMPRESA E ON   AP.ID_APLICACION= E.ID_EMPRESA
        WHERE 1=1 '||T_CONCAT_WHERE;             
   OPEN V_CURSOR FOR T_QUERY;
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_CONSULTAR_PERMISOS(
IS_EMPRESA IN VARCHAR2,
IS_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   
   OPEN V_CURSOR FOR
   SELECT r.MNEMONICO as PERMISO FROM TP_PERMISO r,TP_APLICACION ap,TP_EMPRESA e 
   WHERE r.id_aplicacion=ap.id_aplicacion 
   AND ap.id_empresa=e.id_empresa 
   AND ap.MNEMONICO=IS_APLICACION
   AND e.MNEMONICO=IS_EMPRESA;
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_CONSULTAR_PERMISO_POR_ROL(
IS_ROL          IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;
T_QUERY  VARCHAR2(300);

BEGIN
   OPEN V_CURSOR FOR SELECT P.ID_PERMISO AS CODIGO, NOMBRE, 'TRUE' SELECCION
      FROM TP_PERMISO P
      WHERE P.ID_PERMISO IN ( SELECT ID_PERMISO FROM TR_PERMISO_X_ROL PR WHERE PR.ID_ROL = IS_ROL)
      AND P.ID_APLICACION = (SELECT ID_APLICACION FROM TP_ROL R WHERE R.ID_ROL = IS_ROL)
      UNION
      SELECT P.ID_PERMISO AS CODIGO, NOMBRE, 'FALSE' SELECCION
      FROM TP_PERMISO P
      WHERE P.ID_PERMISO NOT IN ( SELECT ID_PERMISO FROM TR_PERMISO_X_ROL PR WHERE PR.ID_ROL = IS_ROL)
      AND P.ID_APLICACION = (SELECT ID_APLICACION FROM TP_ROL R WHERE R.ID_ROL = IS_ROL);

   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

/*
==========================
STORE PROCEDURE DE POLITICA
===========================*/

PROCEDURE SPS_CONSULTAR_POLITICAS(
IS_OPCION         IN VARCHAR2,
IS_ID_EMPRESA     IN VARCHAR2,
OS_COD_RETORNO    OUT VARCHAR2,
OS_MEN_RETORNO    OUT VARCHAR2,
OS_CURSOR         OUT T_CURSOR
)
IS
   T_QUERY    VARCHAR2(500);
BEGIN 
    IF IS_OPCION = '0' THEN
        T_QUERY := 'SELECT DISTINCT EM.ID_EMPRESA, EM.MNEMONICO AS CODIGO, EM.NOMBRE AS EMPRESA, EM.DESCRIPCION ' ||
                   'FROM TP_EMPRESA EM INNER JOIN TS_ATRIBUTO_EMPRESA AE ON AE.EMPRESA = EM.MNEMONICO';
    END IF;
    
    IF IS_OPCION = '1' THEN
        T_QUERY := 'SELECT DISTINCT AP.ID_APLICACION AS ID_APLICACION, AP.MNEMONICO AS CODIGO, AP.NOMBRE AS APLICACION, ' ||
                   'AP.ESTADO, EM.ID_EMPRESA, EM.NOMBRE AS EMPRESA ' ||
                   'FROM TP_APLICACION AP INNER JOIN TS_ATRIBUTO_APLICACION AE ON AP.MNEMONICO = AE.APLICACION ' ||
                   'INNER JOIN TP_EMPRESA EM ON AP.ID_EMPRESA = EM.ID_EMPRESA ';
        IF (TRIM(IS_ID_EMPRESA) IS NOT NULL) AND (IS_ID_EMPRESA <> '-1') THEN
          T_QUERY := T_QUERY || ' WHERE EM.ID_EMPRESA =' || TO_NUMBER(IS_ID_EMPRESA);
        END IF;
    END IF;
    
   OPEN OS_CURSOR FOR T_QUERY; 
    
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;



PROCEDURE SPS_CONSULTAR_POLITICA(
IS_EVENTO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   OPEN V_CURSOR FOR 
      SELECT ID_POLITICA, EVENTO, CODIGO FROM TP_POLITICA WHERE EVENTO= IS_EVENTO ;       
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_POLITICA_X_EMP(
IS_ID_EMPRESA          IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   OPEN V_CURSOR FOR 
   SELECT * FROM TS_ATRIBUTO_EMPRESA WHERE EMPRESA= (SELECT MNEMONICO FROM TP_EMPRESA WHERE ID_EMPRESA = IS_ID_EMPRESA);
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION 
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_CONSULTAR_POLITICA_X_APLI(
IS_ID_EMPRESA    IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   OPEN V_CURSOR FOR 
   SELECT * FROM TS_ATRIBUTO_APLICACION WHERE APLICACION= (SELECT MNEMONICO FROM TP_APLICACION WHERE ID_APLICACION = IS_ID_APLICACION) 
   AND ID_EMPRESA = TO_NUMBER(IS_ID_EMPRESA);
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_ACTUALIZAR_POLITICA(
IS_ID_POLITICA IN VARCHAR2,
IS_ID_ATRIBUTO IN VARCHAR2,
IS_ID_EMPRESA  IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
IS_VALOR IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2
)

IS
V_CURSOR T_CURSOR;

BEGIN

  UPDATE TS_ATRIBUTO_EMPRESA SET VALOR = IS_VALOR
                             WHERE ID_POLITICA = IS_ID_POLITICA
                             AND ID_ATRIBUTO = IS_ID_ATRIBUTO
                             AND EMPRESA = (SELECT MNEMONICO FROM TP_EMPRESA WHERE ID_EMPRESA = TO_NUMBER(IS_ID_EMPRESA));
                             
   COMMIT;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Politica de empresa actualizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_ACTUALIZAR_POLITICA_APP(
IS_ID_POLITICA IN VARCHAR2,
IS_ID_ATRIBUTO IN VARCHAR2,
IS_ID_EMPRESA  IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
IS_VALOR IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2
) 

IS
V_CURSOR T_CURSOR;

BEGIN
  
  
  UPDATE TS_ATRIBUTO_APLICACION SET VALOR = IS_VALOR
                             WHERE ID_POLITICA = IS_ID_POLITICA
                             AND ID_ATRIBUTO = IS_ID_ATRIBUTO
                             AND APLICACION = (SELECT MNEMONICO FROM TP_APLICACION WHERE ID_APLICACION = IS_ID_APLICACION)
                             AND ID_EMPRESA = TO_NUMBER(IS_ID_EMPRESA);
                             
   COMMIT;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Politica de empresa actualizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

/*
==========================
STORE PROCEDURE DE ATRIBUTO
===========================*/

PROCEDURE SPS_CONSULTAR_ATRIBUTO_EMPRESA(
IS_EMPRESA IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   OPEN V_CURSOR FOR
   SELECT ID_POLITICA, ID_ATRIBUTO, EMPRESA, VALOR  FROM TS_ATRIBUTO_EMPRESA WHERE EMPRESA= IS_EMPRESA ;            
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_ATRIBUTO_APP(
IS_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   OPEN V_CURSOR FOR
   SELECT ID_POLITICA, ID_ATRIBUTO, APLICACION, VALOR  FROM TS_ATRIBUTO_APLICACION WHERE APLICACION= IS_APLICACION ;             
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


/*
==========================
STORE PROCEDURE BLOQUEO
===========================*/


PROCEDURE SPI_REGISTRAR_BLOQUEO(
IS_USUARIO IN VARCHAR2,
IS_EMPRESA IN VARCHAR2,
IS_ESTADO IN VARCHAR2,
IS_FECHA IN TIMESTAMP,
IS_INTENTOSFALLIDOS IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2

)
IS
BEGIN
                
 INSERT INTO TP_BLOQUEO  (
         USUARIO,
         MNEMONICO_EMPRESA, 
         ESTADO,
         FECHA_ACTUALIZACION ,
         INTENTOS_FALLIDOS )
         VALUES(
         IS_USUARIO,
         IS_EMPRESA,
         IS_ESTADO,
         IS_FECHA,
         IS_INTENTOSFALLIDOS); 
 
 COMMIT;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPU_ACTUALIZAR_BLOQUEO(
IS_USUARIO IN VARCHAR2,
IS_ESTADO IN VARCHAR2,
IS_FECHA IN TIMESTAMP,
IS_INTENTOSFALLIDOS IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2

)
IS
BEGIN
                
 UPDATE TP_BLOQUEO SET 
 ESTADO =IS_ESTADO,
 FECHA_ACTUALIZACION =IS_FECHA,
 INTENTOS_FALLIDOS = IS_INTENTOSFALLIDOS
 WHERE USUARIO= IS_USUARIO ; 
 COMMIT;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;

PROCEDURE SPS_CONSULTAR_BLOQUEO(
IS_USUARIO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   OPEN V_CURSOR FOR
   SELECT USUARIO,
   MNEMONICO_EMPRESA,
   ESTADO,
   NVL(TO_CHAR(FECHA_ACTUALIZACION,'YYYY-MM-DD HH24:MI:SS'),' ') AS FECHA_ACTUALIZACION,
   INTENTOS_FALLIDOS
   FROM TP_BLOQUEO WHERE USUARIO= IS_USUARIO ;             
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


/*
==========================
STORE PROCEDURE CLAVEANTIGUA
===========================*/

PROCEDURE SPS_CONSULTAR_CLAVEANTIGUA(
IS_USUARIO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   OPEN V_CURSOR FOR
   SELECT usuario,mnemonico_empresa,old_passwords FROM TP_CLAVE_ANTIGUA WHERE USUARIO= IS_USUARIO ;             
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPI_REGISTRAR_CLAVEANTIGUA(
IS_USUARIO IN VARCHAR2,
IS_EMPRESA IN VARCHAR2,
IS_PASSWORDS IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2

)
IS
BEGIN
                
 INSERT INTO TP_CLAVE_ANTIGUA  (
         USUARIO,
         MNEMONICO_EMPRESA, 
         OLD_PASSWORDS )
         VALUES(
         IS_USUARIO,
         IS_EMPRESA,
         IS_PASSWORDS); 
 
 COMMIT;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Clave antigua registrada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPU_ACTUALIZAR_CLAVEANTIGUA(
PASSWORDS IN VARCHAR2,
IS_USUARIO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2

)
IS
BEGIN
                
 UPDATE TP_CLAVE_ANTIGUA SET 
        OLD_PASSWORDS = PASSWORDS
        WHERE USUARIO=IS_USUARIO; 
 
 COMMIT;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Clave antigua actualizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


/*
==========================
STORE PROCEDURE DE LLAVE
===========================*/

PROCEDURE SPI_REGISTRAR_LLAVE(
IS_NOMBRE IN VARCHAR2,
IS_VALOR_NUEVO IN VARCHAR2,
IS_TIPO_LLAVE IN VARCHAR2,
IS_TIPO_GENERACION IN VARCHAR2,
IS_ESTADO IN VARCHAR,
IS_AUD_USUARIO_CREACION IN VARCHAR2,
IS_AUD_FECHA_CREACION IN TIMESTAMP,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2

)
IS

BEGIN

 INSERT INTO TP_LLAVE(
                ID_LLAVE,
                NOMBRE,
                VALOR_ANTERIOR,
                VALOR_NUEVO,
                TIPO_LLAVE,
                TIPO_GENERACION,
                ESTADO,
                AUD_USU_CREAC,
                AUD_FEC_CREAC
                )
            VALUES(
                SEQ_LLAVE.NEXTVAL,
                IS_NOMBRE,
                IS_VALOR_NUEVO,
                IS_VALOR_NUEVO,
                IS_TIPO_LLAVE,
                IS_TIPO_GENERACION,
                IS_ESTADO,
                IS_AUD_USUARIO_CREACION,
                IS_AUD_FECHA_CREACION);
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Llave registrada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;

PROCEDURE SPU_ACTUALIZAR_LLAVE(
IS_ID_LLAVE IN NUMBER,
IS_NOMBRE IN VARCHAR2,
IS_VALOR_NUEVO IN VARCHAR2,
IS_TIPO_LLAVE IN VARCHAR2,
IS_TIPO_GENERACION IN VARCHAR2,
IS_ESTADO IN VARCHAR,
IS_AUD_USUARIO_MODIFICACION IN VARCHAR2,
IS_AUD_FECHA_MODIFICACION IN TIMESTAMP,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2

)
IS
V_VALOR_ANTERIOR TP_LLAVE.VALOR_ANTERIOR%TYPE;
BEGIN

    SELECT VALOR_NUEVO INTO V_VALOR_ANTERIOR
      FROM TP_LLAVE
        WHERE ID_LLAVE= IS_ID_LLAVE;    

    UPDATE TP_LLAVE SET
                NOMBRE = IS_NOMBRE,
                VALOR_ANTERIOR = V_VALOR_ANTERIOR,
                VALOR_NUEVO = IS_VALOR_NUEVO,
                TIPO_LLAVE = IS_TIPO_LLAVE,
                TIPO_GENERACION = IS_TIPO_GENERACION,
                ESTADO = IS_ESTADO,
                AUD_USU_MODIF = IS_AUD_USUARIO_MODIFICACION,
                AUD_FEC_MODIF = IS_AUD_FECHA_MODIFICACION
                WHERE ID_LLAVE= IS_ID_LLAVE;
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Llave actualizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;

PROCEDURE SPD_ELIMINAR_LLAVE(
IS_ID_LLAVE IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
)
IS

BEGIN

 DELETE TP_LLAVE WHERE ID_LLAVE= IS_ID_LLAVE;
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Llave eliminada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;

PROCEDURE SPS_CONSULTAR_LLAVE_SEGUN_TIPO(
IS_TIPO_LLAVE IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;
BEGIN  
  
   OPEN V_CURSOR FOR
   
   SELECT  
	  ID_LLAVE,
	  NOMBRE,
	  VALOR_ANTERIOR,
	  VALOR_NUEVO,
	  TIPO_LLAVE,
	  TIPO_GENERACION,
	  ESTADO	     
   FROM TP_LLAVE 
   WHERE TIPO_LLAVE= IS_TIPO_LLAVE;   
   
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta Llave realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;


/*
==========================
STORE PROCEDURE HOARIO
===========================*/
PROCEDURE SPS_CONSULTAR_HORARIO(
IS_HORARIO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR)
IS
V_CURSOR T_CURSOR;

BEGIN
                
   OPEN V_CURSOR FOR 
   SELECT * FROM TP_HORARIO H
   WHERE H.ID_HORARIO = IS_HORARIO;
   OS_CURSOR := V_CURSOR;
   
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;




PROCEDURE SPS_CONSULTAR_HORARIO_EMPRESA(
IS_EMPRESA IN NUMBER,
IS_CODIGO_HORARIO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;
BEGIN
   
   OPEN V_CURSOR FOR
   SELECT h.ID_EMPRESA,
    h.MNEMONICO,
    h.MAC as MAC,
    h.TIPO,
    d.ID_HORARIO,
    ID_DETALLE,
    POR_HORA,
    HORA_INICIO,
    HORA_FIN,
    POR_DIA,
    LUNES,
    MARTES,
    MIERCOLES,
    JUEVES,
    VIERNES,
    SABADO,
    DOMINGO
    FROM TP_HORARIO h, TS_HORARIO_DETALLE d
    WHERE h.ID_HORARIO=d.ID_HORARIO
    AND h.ID_EMPRESA=IS_EMPRESA 
    AND h.MNEMONICO=IS_CODIGO_HORARIO;
   OS_CURSOR :=V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta Llave realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;


PROCEDURE SPS_CONSULTAR_HORARIO_TODAS(
IS_NOMBRE IN VARCHAR2,
IS_TIPO IN VARCHAR2,
IS_EMPRESA IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
V_CURSOR T_CURSOR;
T_CONCATENAR_WHERE VARCHAR2(500);

BEGIN
   IF IS_NOMBRE IS NOT NULL THEN
     T_CONCATENAR_WHERE := 'AND UPPER(H.NOMBRE) LIKE UPPER(''%'||IS_NOMBRE||'%'')';
   END IF;
   
   IF IS_TIPO IS NOT NULL THEN
     T_CONCATENAR_WHERE := T_CONCATENAR_WHERE||' AND H.TIPO = '''||IS_TIPO||'''';
   END IF;
   
   IF IS_EMPRESA IS NOT NULL THEN
     T_CONCATENAR_WHERE := T_CONCATENAR_WHERE||' AND H.ID_EMPRESA = '''||IS_EMPRESA||'''';
   END IF;
         
   T_QUERY := ' SELECT H.ID_HORARIO, H.MNEMONICO ,H.NOMBRE, H.TIPO, E.NOMBRE AS NOMB_EMPRESA
                FROM TP_HORARIO H JOIN TP_EMPRESA E 
                ON E.ID_EMPRESA = H.ID_EMPRESA WHERE 1= 1 '||T_CONCATENAR_WHERE; 
                
   
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := T_QUERY;--'Consulta realizada correctamente.';
   
   OPEN V_CURSOR FOR T_QUERY;
   OS_CURSOR := V_CURSOR;

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPI_REGISTRAR_HORARIO(
IS_ID_APLICACION  IN NUMBER,
IS_ID_EMPRESA     IN NUMBER,
IS_ID_USUARIO     IN NUMBER,
IS_TIPO       IN VARCHAR2,
IS_MNEMONICO     IN VARCHAR2,
IS_NOMBRE       IN VARCHAR2,
IS_MAC         IN VARCHAR2,
IS_USUARIO      IN VARCHAR2,
OS_ID_HORARIO       OUT NUMBER,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2
)
IS 
NUMBER_HORARIO NUMBER;

BEGIN
  IF IS_TIPO = 'APLICACION' THEN
    SELECT COUNT(*) INTO NUMBER_HORARIO 
      FROM TP_HORARIO 
      WHERE ID_APLICACION=IS_ID_APLICACION
      AND ID_EMPRESA = IS_ID_EMPRESA;  
  ELSIF IS_TIPO = 'USUARIO' THEN
    SELECT COUNT(*) INTO NUMBER_HORARIO 
      FROM TP_HORARIO 
      WHERE ID_USUARIO=IS_ID_USUARIO
      AND ID_EMPRESA = IS_ID_EMPRESA;
  END IF;
   
   IF NUMBER_HORARIO = 0 THEN
       INSERT INTO TP_HORARIO
        (ID_HORARIO, ID_APLICACION, ID_EMPRESA, ID_USUARIO,TIPO, MNEMONICO, NOMBRE,MAC,AUD_FEC_CREAC,AUD_USU_CREAC) 
        VALUES
        (SEQ_HORARIO.NEXTVAL ,IS_ID_APLICACION,IS_ID_EMPRESA,IS_ID_USUARIO,IS_TIPO,IS_MNEMONICO,IS_NOMBRE,IS_MAC, SYSDATE, IS_USUARIO)
        RETURNING ID_HORARIO INTO OS_ID_HORARIO;
       
        COMMIT;
         OS_COD_RETORNO := '00';
         OS_MEN_RETORNO := 'Horario registrado correctamente.';
   
    ELSE
      OS_COD_RETORNO := '10';
      OS_MEN_RETORNO := 'El Horario ya se encuentra registrado.';
      
    END IF;  
    

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;  
END;

PROCEDURE SPI_REGISTRAR_HORARIO_DET(
IS_ID_HORARIO IN NUMBER,
IS_DOMINGO IN NUMBER,
IS_HORA_FIN IN VARCHAR2,
IS_HORA_INICIO IN VARCHAR,
IS_JUEVES IN NUMBER,
IS_LUNES IN NUMBER,
IS_MARTES IN NUMBER,
IS_MIERCOLES IN NUMBER,
IS_POR_DIA IN NUMBER,
IS_POR_HORA IN NUMBER,
IS_SABADO IN NUMBER,
IS_VIERNES IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
)
IS 

BEGIN  
    INSERT INTO TS_HORARIO_DETALLE
    (ID_HORARIO, ID_DETALLE , DOMINGO, HORA_FIN , HORA_INICIO, JUEVES, LUNES, 
     MARTES, MIERCOLES, POR_DIA, POR_HORA, SABADO, VIERNES) 
    VALUES
    (IS_ID_HORARIO, SEQ_HORARIODETALLE.NEXTVAL ,IS_DOMINGO,IS_HORA_FIN,IS_HORA_INICIO,
     IS_JUEVES,IS_LUNES,IS_MARTES,IS_MIERCOLES,IS_POR_DIA,IS_POR_HORA,IS_SABADO,IS_VIERNES);

  COMMIT;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Detalle de horario registrado correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;  
END;


PROCEDURE SPU_ACTUALIZAR_HORARIO(
IS_ID_APLICACION NUMBER,
IS_ID_EMPRESA    NUMBER,
IS_ID_USUARIO    IN VARCHAR2,
IS_TIPO      IN VARCHAR2,
IS_MNEMONICO    IN VARCHAR2,
IS_NOMBRE      IN VARCHAR2,
IS_MAC        IN VARCHAR2,
IS_USUARIO       IN VARCHAR2,
IS_ID_HORARIO    IN NUMBER,
OS_COD_RETORNO   OUT VARCHAR2,
OS_MEN_RETORNO   OUT VARCHAR2
)

IS 
BEGIN
        UPDATE TP_HORARIO SET 
        ID_APLICACION = IS_ID_APLICACION,
        ID_EMPRESA = IS_ID_EMPRESA,
        ID_USUARIO = IS_ID_USUARIO,
        TIPO = IS_TIPO,
        MNEMONICO = IS_MNEMONICO,
        NOMBRE = IS_NOMBRE,
        MAC = IS_MAC,
    AUD_FEC_MODIF = SYSDATE,
    AUD_USU_MODIF = IS_USUARIO 
        WHERE ID_HORARIO=IS_ID_HORARIO;        

  COMMIT;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Registro actualizado correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;  
END;

PROCEDURE SPU_ACTUALIZAR_HORARIO_DET(
IS_ID_HORARIO IN NUMBER,
IS_ID_DETALLE IN NUMBER,
IS_DOMINGO IN NUMBER,
IS_HORA_FIN IN VARCHAR2,
IS_HORA_INICIO IN VARCHAR,
IS_JUEVES IN NUMBER,
IS_LUNES IN NUMBER,
IS_MARTES IN NUMBER,
IS_MIERCOLES IN NUMBER,
IS_POR_DIA IN NUMBER,
IS_POR_HORA IN NUMBER,
IS_SABADO IN NUMBER,
IS_VIERNES IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
)

IS 
BEGIN
         UPDATE TS_HORARIO_DETALLE SET 
         DOMINGO = IS_DOMINGO,
         HORA_FIN = IS_HORA_FIN, 
         HORA_INICIO = IS_HORA_INICIO, 
         JUEVES = IS_JUEVES, 
         LUNES = IS_LUNES, 
         MARTES = IS_MARTES,  
         MIERCOLES = IS_MIERCOLES, 
         POR_DIA = IS_POR_DIA , 
         POR_HORA = IS_POR_HORA, 
         SABADO = IS_SABADO, 
         VIERNES  = IS_VIERNES  
         WHERE ID_HORARIO=IS_ID_HORARIO
         AND ID_DETALLE = IS_ID_DETALLE;   

  COMMIT;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Registro actualizado correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;  
END;


PROCEDURE SPD_ELIMINAR_HORARIO(
IS_ID_HORARIO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2)
IS
BEGIN 
  
DELETE FROM TP_HORARIO WHERE ID_HORARIO = IS_ID_HORARIO;
SPD_ELIMINAR_HORARIO_DET(IS_ID_HORARIO, OS_COD_RETORNO, OS_MEN_RETORNO);

IF OS_COD_RETORNO = '00' THEN   
  COMMIT;
ELSE
  ROLLBACK;
END IF; 
  
 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;  
END;


PROCEDURE SPD_ELIMINAR_HORARIO_DET(
IS_ID_HORARIO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2)
IS
BEGIN 
  
DELETE FROM TS_HORARIO_DETALLE WHERE ID_HORARIO = IS_ID_HORARIO;
        
COMMIT;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Registro eliminado correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;  
END;


PROCEDURE SPS_OBTENER_CODIGO_HORARIO(
IS_TIPO IN VARCHAR2,
IS_ID_DATA IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR)

IS
V_CURSOR T_CURSOR;   
BEGIN
  IF IS_TIPO = 'USUARIO' THEN
     OPEN V_CURSOR FOR 
     SELECT  USUARIO AS MNEMONICO, NOMBRE  FROM TP_USUARIO
     WHERE ID_USUARIO = IS_ID_DATA; 
   ELSE 
     OPEN V_CURSOR FOR 
     SELECT  MNEMONICO AS MNEMONICO, NOMBRE  FROM TP_APLICACION
     WHERE ID_APLICACION = IS_ID_DATA;
     
   END IF;
  
  OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';
  
 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM; 
  
END;


PROCEDURE SPS_CONSULTAR_HORARIO_DET(
IS_HORARIO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR)
IS
V_CURSOR T_CURSOR;

BEGIN
                
   OPEN V_CURSOR FOR 
   SELECT * FROM TS_HORARIO_DETALLE HD
   WHERE HD.ID_HORARIO = IS_HORARIO;
   
   OS_CURSOR := V_CURSOR;
   
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_USUARIO_ADAPTER(
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
V_CURSOR T_CURSOR;

BEGIN
   
   OPEN V_CURSOR FOR
   SELECT ID_USUARIO AS CODIGO, USUARIO AS NOMBRE
   FROM TP_USUARIO;
   
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;


PROCEDURE SPS_CONSULTAR_USUARIOS_EMP(
  IS_ID_EMPRESA           IN VARCHAR2,
  OS_COD_RETORNO          OUT VARCHAR2,
  OS_MEN_RETORNO          OUT VARCHAR2,
  OS_CURSOR               OUT T_CURSOR
)
IS
BEGIN
  OPEN OS_CURSOR FOR 
  SELECT ID_USUARIO AS CODIGO, USUARIO AS NOMBRE from TP_USUARIO 
  WHERE ID_EMPRESA = IS_ID_EMPRESA ;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Empresa registrada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
  
END;

/*
==========================
STORE PROCEDURE DE IMPORTAR
===========================*/
PROCEDURE SPI_IMPORTAR_TEMPLATE(
  IS_MNEMONICO    IN VARCHAR2,
  IS_NOMBRE       IN VARCHAR2,
  IS_ESTADO       IN VARCHAR2,
  IS_TIPO         IN VARCHAR2,
  IS_DESCRIPCION  IN VARCHAR2,
  IS_ID_EMPRESA   IN VARCHAR2,
  IS_ID_APLICACION IN VARCHAR2,
  IS_USUARIO      IN VARCHAR2,
  OS_COD_RETORNO  OUT VARCHAR2,
  OS_MEN_RETORNO  OUT VARCHAR2,
  OS_ID_TEMPLATE  OUT NUMBER
) 
IS
  CONT  NUMBER;
BEGIN
  
  IF IS_TIPO = 'EMPRESA' THEN
    SELECT COUNT(1) INTO CONT FROM TP_TEMPLATE WHERE MNEMONICO = IS_MNEMONICO AND TIPO = IS_TIPO;
    INSERT_XML_EMP(IS_DESCRIPCION, IS_USUARIO, OS_COD_RETORNO, OS_MEN_RETORNO);
  END IF;
  
  IF IS_TIPO = 'APLICACION' THEN
    SELECT COUNT(1) INTO CONT FROM TP_TEMPLATE WHERE MNEMONICO = IS_MNEMONICO AND TIPO = IS_TIPO AND ID_EMPRESA = TO_NUMBER(IS_ID_EMPRESA);
    INSERT_XML_APP(IS_DESCRIPCION, IS_ID_EMPRESA, IS_USUARIO, '/APLICACION', OS_COD_RETORNO, OS_MEN_RETORNO);
  END IF;
  
  IF (CONT = 0) AND (TRIM(OS_COD_RETORNO) IS NOT NULL) THEN 
 
    INSERT INTO TP_TEMPLATE VALUES(SEQ_TEMPLATE.NEXTVAL, IS_MNEMONICO, IS_NOMBRE, IS_ESTADO, IS_TIPO, SYSDATE, NULL, IS_USUARIO, NULL, IS_DESCRIPCION, TO_NUMBER(IS_ID_EMPRESA))
    RETURNING ID_TEMPLATE INTO OS_ID_TEMPLATE;  
    
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Operacion realizada correctamente.';
    COMMIT;
  ELSE
    OS_COD_RETORNO := '10';
    OS_MEN_RETORNO := 'El template ya existe';
    ROLLBACK;
  END IF;

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;


PROCEDURE SPS_CONSULTAR_IMPORTAR(
IS_TIPO                IN VARCHAR2,
IS_ID_EMPRESA          IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
BEGIN
  
  IF IS_TIPO = '0' THEN
  
    T_QUERY := 'SELECT TE.ID_TEMPLATE, TE.MNEMONICO, EM.NOMBRE AS "EMPRESA", EM.ID_EMPRESA AS "ID_EMPRESA", TE.DESCRIPCION ' ||
               'FROM TP_TEMPLATE TE ' ||
               'INNER JOIN TP_EMPRESA EM ON TE.MNEMONICO = EM.MNEMONICO ' ||
               'WHERE TE.TIPO = ''EMPRESA'' ';
    IF IS_ID_EMPRESA <> '-1' THEN           
      T_QUERY := T_QUERY || ' AND EM.ID_EMPRESA = ' || TO_NUMBER(IS_ID_EMPRESA);
    END IF;
  END IF;
  
  IF IS_TIPO = '1' THEN
    T_QUERY := 'SELECT TE.ID_TEMPLATE, TE.MNEMONICO, EM.NOMBRE AS "EMPRESA", EM.ID_EMPRESA AS "ID_EMPRESA", TE.DESCRIPCION, ' ||
               'AP.ID_APLICACION, AP.NOMBRE AS "APLICACION" ' ||
               'FROM TP_TEMPLATE TE ' ||
               'INNER JOIN TP_APLICACION AP ON AP.MNEMONICO = TE.MNEMONICO ' ||
               'INNER JOIN TP_EMPRESA EM ON AP.ID_EMPRESA = EM.ID_EMPRESA ' ||
               'WHERE TE.TIPO = ''APLICACION'' ';
    IF IS_ID_EMPRESA <> '-1' THEN           
      T_QUERY := T_QUERY || ' AND EM.ID_EMPRESA = ' || TO_NUMBER(IS_ID_EMPRESA);
    END IF;
  END IF; 
  
  OPEN OS_CURSOR FOR T_QUERY;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
  
END;



PROCEDURE SPI_REGISTRAR_TEMPLATE(
  IS_MNEMONICO    IN VARCHAR2,
  IS_NOMBRE       IN VARCHAR2,
  IS_ESTADO       IN VARCHAR2,
  IS_TIPO         IN VARCHAR2,
  IS_DESCRIPCION  IN CLOB,
  IS_ID_EMPRESA   IN VARCHAR2,
  IS_ID_APLICACION IN VARCHAR2,
  IS_USUARIO      IN VARCHAR2,
  OS_COD_RETORNO  OUT VARCHAR2,
  OS_MEN_RETORNO  OUT VARCHAR2,
  OS_ID_TEMPLATE  OUT NUMBER
) 
IS
  IS_MNEMO VARCHAR2(255);
  CONT  NUMBER;
BEGIN 
  
  IF IS_TIPO = 'EMPRESA' THEN
    SELECT MNEMONICO INTO IS_MNEMO FROM TP_EMPRESA WHERE ID_EMPRESA = TO_NUMBER(IS_ID_EMPRESA);
    SELECT COUNT(1) INTO CONT FROM TP_TEMPLATE WHERE MNEMONICO = IS_MNEMO AND TIPO = IS_TIPO;
  END IF;
  
  IF IS_TIPO = 'APLICACION' THEN
    SELECT MNEMONICO INTO IS_MNEMO FROM TP_APLICACION WHERE ID_APLICACION = TO_NUMBER(IS_ID_APLICACION);
    SELECT COUNT(1) INTO CONT FROM TP_TEMPLATE WHERE MNEMONICO = IS_MNEMO AND TIPO = IS_TIPO AND ID_EMPRESA = TO_NUMBER(IS_ID_EMPRESA);
  END IF;
  
  IF CONT = 0 THEN 
   
    INSERT INTO TP_TEMPLATE VALUES(SEQ_TEMPLATE.NEXTVAL, IS_MNEMO, IS_NOMBRE, IS_ESTADO, IS_TIPO, SYSDATE, NULL, IS_USUARIO, NULL, IS_DESCRIPCION, TO_NUMBER(IS_ID_EMPRESA))
    RETURNING ID_TEMPLATE INTO OS_ID_TEMPLATE;  
    
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Operacion realizada correctamente.';
  ELSE
    OS_COD_RETORNO := '10';
    OS_MEN_RETORNO := 'El template ya existe';
  END IF;

  COMMIT;

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;
END;

PROCEDURE SPS_CONSULTAR_PERMISO_ROL(
  IS_ID_ROL  IN VARCHAR2,
  OS_COD_RETORNO    OUT VARCHAR2,
  OS_MEN_RETORNO    OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
)
IS 
  T_QUERY VARCHAR2(250);
BEGIN
  
  T_QUERY := 'SELECT P.MNEMONICO, P.NOMBRE FROM TP_PERMISO P INNER JOIN TR_PERMISO_X_ROL PR ON PR.ID_PERMISO = P.ID_PERMISO ' || 
             'WHERE PR.ID_ROL =' || IS_ID_ROL;
  
  OPEN OS_CURSOR FOR T_QUERY;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;


END;



PROCEDURE SPS_CONSULTAR_ROL_X_APP(
  IS_ID_APLICACION  IN VARCHAR2,
  OS_COD_RETORNO    OUT VARCHAR2,
  OS_MEN_RETORNO    OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
)
IS 
  T_QUERY VARCHAR2(250);
BEGIN
  
  T_QUERY := 'SELECT R.ID_ROL, R.MNEMONICO, R.NOMBRE FROM TP_ROL R WHERE R.ID_APLICACION =' || IS_ID_APLICACION;
  
  OPEN OS_CURSOR FOR T_QUERY;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;


END;


PROCEDURE SPS_CONSULTAR_APP(
  IS_ID_APLICACION  IN VARCHAR2,
  OS_COD_RETORNO    OUT VARCHAR2,
  OS_MEN_RETORNO    OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
)
IS 
  T_QUERY VARCHAR2(250);
BEGIN
  
  T_QUERY := 'SELECT P.MNEMONICO, P.NOMBRE FROM TP_PERMISO P WHERE P.ID_APLICACION =' || IS_ID_APLICACION;
  
  OPEN OS_CURSOR FOR T_QUERY;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;


END;



PROCEDURE SPS_CONSULTAR_ROL_USUARIO(
  IS_ID_EMPRESA     IN VARCHAR2,
  IS_ID_USUARIO     IN VARCHAR2,
  OS_COD_RETORNO    OUT VARCHAR2,
  OS_MEN_RETORNO    OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
)
IS
  T_QUERY VARCHAR2(1000);
BEGIN

  T_QUERY := 'SELECT R.MNEMONICO, R.NOMBRE FROM TP_ROL R ' ||
             'INNER JOIN TR_ROL_X_USUARIO RU ON RU.ID_ROL = R.ID_ROL ' ||
             'INNER JOIN TP_USUARIO U ON RU.ID_USUARIO = U.ID_USUARIO ' ||
             'INNER JOIN TP_EMPRESA E ON U.ID_EMPRESA = E.ID_EMPRESA ' ||
             'WHERE E.ID_EMPRESA=' || IS_ID_EMPRESA  ||' AND U.ID_USUARIO =' || IS_ID_USUARIO;

  OPEN OS_CURSOR FOR T_QUERY;
  
  OS_COD_RETORNO := '00';
  OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;


END;



PROCEDURE SPU_ACTUALIZAR_USUARIO_ESTADO(
IS_ID_USUARIO IN NUMBER,
IS_ESTADO IN VARCHAR2,
IS_CONTRASENA IN VARCHAR2,
IS_FECHACAMBIOCLAVE IN TIMESTAMP,
IS_USUARIO_AGR     IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2

)
IS

BEGIN

 UPDATE TP_USUARIO SET                
        ESTADO= IS_ESTADO,  
        CONTRASENA=IS_CONTRASENA,
        FECHA_CAMBIO_CLAVE = IS_FECHACAMBIOCLAVE,              

        AUD_FEC_MODIF = SYSDATE,
        AUD_USU_MODIF = IS_USUARIO_AGR 
        WHERE ID_USUARIO=IS_ID_USUARIO;             
    COMMIT;
    OS_COD_RETORNO := '00';
    OS_MEN_RETORNO := 'Estado Usuario actualizado correctamente.';


 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


PROCEDURE SPS_CONSULTAR_PERMISO_IMPORT(
IS_ID_APLICACION IN VARCHAR2,
IS_MNEMONICO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
)
IS
T_QUERY VARCHAR2(1000);
V_CURSOR T_CURSOR;
T_CONCAT_WHERE VARCHAR(300);

BEGIN

   IF IS_MNEMONICO IS NOT NULL THEN
      T_CONCAT_WHERE := ' AND P.MNEMONICO = '''|| IS_MNEMONICO||'''';
   END IF;
   
   IF IS_ID_APLICACION IS NOT NULL THEN
      T_CONCAT_WHERE := T_CONCAT_WHERE||' AND P.ID_APLICACION='||IS_ID_APLICACION;
   END IF;


   T_QUERY := 'SELECT P.ID_PERMISO,P.MNEMONICO,P.NOMBRE AS P_NOMBRE
				FROM TP_PERMISO P
				WHERE 1=1 '||T_CONCAT_WHERE;             
   OPEN V_CURSOR FOR T_QUERY;
   OS_CURSOR := V_CURSOR;
   OS_COD_RETORNO := '00';
   OS_MEN_RETORNO := 'Consulta realizada correctamente.';

 EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
      OS_COD_RETORNO := '01';
      OS_MEN_RETORNO := SQLCODE||'.'||SQLERRM;

END;


FUNCTION FUN_EMPRESA_X_APLICACION(IS_ID_APLICACION IN NUMBER) RETURN VARCHAR2
  IS
  OS_EMPRESA  VARCHAR2(150);
  BEGIN
    SELECT E.NOMBRE  INTO OS_EMPRESA
         FROM TP_EMPRESA E, TP_APLICACION A
         WHERE E.ID_EMPRESA = A.ID_APLICACION
         AND A.ID_APLICACION = IS_ID_APLICACION ; 
    
  RETURN  OS_EMPRESA;
 EXCEPTION
    WHEN OTHERS THEN
       RETURN ''; 
END ;

END PKG_SCA;