create or replace
PACKAGE "PKG_SCA" as

TYPE T_CURSOR   IS REF CURSOR;

/*
==========================
STORE PROCEDURE DE TEMPLATE
===========================*/
PROCEDURE SPS_CONSULTAR_IMPORTAR(
IS_TIPO                IN VARCHAR2,
IS_ID_EMPRESA          IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPD_ELIMINAR_TEMPLATE(
  IS_ID_TEMPLATE IN VARCHAR2,
  OS_COD_RETORNO  OUT VARCHAR2,
  OS_MEN_RETORNO  OUT VARCHAR2
);

PROCEDURE SPU_ACTUALIZAR_TEMPLATE(
IS_ID_TEMPLATE IN VARCHAR2,
IS_NOMBRE      IN VARCHAR2,
IS_DESCRIPCION IN VARCHAR2,
IS_USUARIO     IN VARCHAR2,
OS_COD_RETORNO  OUT VARCHAR2,
OS_MEN_RETORNO  OUT VARCHAR2
);

PROCEDURE SPS_CONSULTAR_TEMPLATE(
  IS_ID_TEMPLATE IN VARCHAR2,
  OS_COD_RETORNO  OUT VARCHAR2,
  OS_MEN_RETORNO  OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_TEMPLATES(
  IS_ID_EMPRESA     IN VARCHAR2,
  IS_ID_APLICACION  IN VARCHAR2,
  IS_NOMBRE         IN VARCHAR2,
  IS_TIPO           IN VARCHAR2,
  OS_COD_RETORNO  OUT VARCHAR2,
  OS_MEN_RETORNO  OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
);



/*
============================
STORE PROCEDURE DE IMPORTAR 
============================*/
PROCEDURE SPI_IMPORTAR_TEMPLATE(
  IS_MNEMONICO    IN VARCHAR2,
  IS_NOMBRE       IN VARCHAR2,
  IS_ESTADO       IN VARCHAR2,
  IS_TIPO         IN VARCHAR2,
  IS_DESCRIPCION  IN VARCHAR2,
  IS_ID_EMPRESA   IN VARCHAR2,
  IS_ID_APLICACION IN VARCHAR2,
  IS_USUARIO      IN VARCHAR2,
  OS_COD_RETORNO  OUT VARCHAR2,
  OS_MEN_RETORNO  OUT VARCHAR2,
  OS_ID_TEMPLATE  OUT NUMBER
);

PROCEDURE SPI_REGISTRAR_TEMPLATE(
  IS_MNEMONICO    IN VARCHAR2,
  IS_NOMBRE       IN VARCHAR2,
  IS_ESTADO       IN VARCHAR2,
  IS_TIPO         IN VARCHAR2,
  IS_DESCRIPCION  IN CLOB,
  IS_ID_EMPRESA   IN VARCHAR2,
  IS_ID_APLICACION IN VARCHAR2,
  IS_USUARIO    IN VARCHAR2,
  OS_COD_RETORNO  OUT VARCHAR2,
  OS_MEN_RETORNO  OUT VARCHAR2,
  OS_ID_TEMPLATE  OUT NUMBER
);

PROCEDURE SPS_CONSULTAR_PERMISO_ROL(
  IS_ID_ROL  IN VARCHAR2,
  OS_COD_RETORNO    OUT VARCHAR2,
  OS_MEN_RETORNO    OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
);

/*
==========================
STORE PROCEDURE DE AUDITORIA
===========================*/
PROCEDURE SPS_CONSULTAR_AUDITORIA(
IS_USUARIO             IN VARCHAR2,
IS_METODO              IN VARCHAR2,
IS_IP                  IN VARCHAR2,
IS_EMPRESA             IN VARCHAR2,
IS_FECHA_INICIO        IN VARCHAR2,
IS_FECHA_FIN           IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);


/*
==========================
STORE PROCEDURE DE LOGIN
===========================*/

PROCEDURE SPS_CONSULTAR_CREDENCIALES(
IS_USUARIO            IN VARCHAR2,
OS_COD_RETORNO        OUT VARCHAR2,
OS_MEN_RETORNO        OUT VARCHAR2,
OS_CURSOR             OUT T_CURSOR
);


/*
==========================
STORE PROCEDURE DE EMPRESA
===========================*/
PROCEDURE SPS_CONSULTAR_EMPRESA_DATA(
  IS_TIPO IN NUMBER,
  OS_COD_RETORNO       OUT VARCHAR2,
  OS_MEN_RETORNO       OUT VARCHAR2,
  OS_CURSOR            OUT T_CURSOR
);

PROCEDURE SPI_REGISTRAR_EMPRESA(
IS_MNEMONICO IN VARCHAR2,
IS_NOMBRE IN VARCHAR2,
IS_DESCRIPCION IN VARCHAR2,
IS_ESTADO IN VARCHAR2,
IS_USUARIO IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_COD_EMPRESA           OUT NUMBER
);

PROCEDURE SPU_ACTUALIZAR_EMPRESA(
IS_ID_EMPRESA   IN NUMBER,
IS_NOMBRE     IN VARCHAR2,
IS_DESCRIPCION  IN VARCHAR2,
IS_ESTADO     IN VARCHAR2,
IS_USUARIO      IN VARCHAR2,
OS_COD_RETORNO  OUT VARCHAR2,
OS_MEN_RETORNO  OUT VARCHAR2
);

PROCEDURE SPD_ELIMINAR_EMPRESA(
IS_ID_EMPRESA IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);

PROCEDURE SPS_CONSULTAR_EMPRESA(
IS_ID_EMPRESA          IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_EMPRESA_TODAS(
IS_NOMBRE VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_PERM_TODAS(
IS_PERMISO IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
IS_ID_EMPRESA IN VARCHAR2,
IS_TIPO_PERMISO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);


/*
==========================
STORE PROCEDURE DE USUARIO
===========================*/

PROCEDURE SPS_USUARIO_CAMBIAR_PASS(
IS_ID_USUARIO       IN NUMBER,
IS_MAC              IN VARCHAR2,
IS_PASSWORD         IN VARCHAR2,
IS_USUARIO      IN VARCHAR2,
OS_EMAIL            OUT VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2
);

PROCEDURE SPI_REGISTRAR_USUARIO(
IS_ID_EMPRESA IN NUMBER,
IS_USUARIO IN VARCHAR2,
IS_CONTRASENA IN VARCHAR2,
IS_APELLIDOMATERNO IN VARCHAR2,
IS_APELLIDOPATERNO IN VARCHAR2,
IS_NOMBRE IN VARCHAR2,
IS_CORREO IN VARCHAR2,
IS_ESTADO IN VARCHAR,
IS_TIPODOCUMENTO IN VARCHAR2,
IS_NUMERODOCUMENTO IN VARCHAR2,
IS_TELEFONO IN VARCHAR2,
IS_FECHACAMBIOCLAVE IN TIMESTAMP,
IS_FECHALOGIN IN TIMESTAMP,
IS_MAC IN VARCHAR2,
IS_USUARIO_AGR  IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_ID_USUARIO            OUT NUMBER
);

PROCEDURE SPU_ACTUALIZAR_USUARIO(
IS_ID_USUARIO IN NUMBER,
IS_ID_EMPRESA IN NUMBER,
IS_USUARIO IN VARCHAR2,
--IS_CONTRASENA IN VARCHAR2,
--IS_APELLIDOMATERNO IN VARCHAR2,
IS_APELLIDOPATERNO IN VARCHAR2,
IS_NOMBRE IN VARCHAR2,
IS_CORREO IN VARCHAR2,
IS_ESTADO IN VARCHAR,
IS_TIPODOCUMENTO IN VARCHAR2,
IS_NUMERODOCUMENTO IN VARCHAR2,
IS_TELEFONO IN VARCHAR2,
--IS_FECHACAMBIOCLAVE IN TIMESTAMP,
--IS_FECHALOGIN IN TIMESTAMP,
IS_MAC IN VARCHAR2,
IS_USUARIO_AGR     IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);


PROCEDURE SPU_ACTUALIZAR_DATOS(
IS_ID_USUARIO IN NUMBER,
IS_ID_EMPRESA IN NUMBER,
IS_USUARIO IN VARCHAR2,
IS_CONTRASENA IN VARCHAR2,
IS_APELLIDOMATERNO IN VARCHAR2,
IS_APELLIDOPATERNO IN VARCHAR2,
IS_NOMBRE IN VARCHAR2,
IS_CORREO IN VARCHAR2,
IS_ESTADO IN VARCHAR,
IS_TIPODOCUMENTO IN VARCHAR2,
IS_NUMERODOCUMENTO IN VARCHAR2,
IS_TELEFONO IN VARCHAR2,
IS_FECHACAMBIOCLAVE IN TIMESTAMP,
IS_FECHALOGIN IN TIMESTAMP,
IS_MAC IN VARCHAR2,
IS_FECHAMODIFICACION IN TIMESTAMP,
IS_USUARIOMODIFICACION IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);

PROCEDURE SPD_ELIMINAR_USUARIO(
IS_ID_USUARIO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);

PROCEDURE SPS_CONSULTAR_USUARIO(
IS_COD_USUARIO        IN NUMBER, 
IS_USUARIO            IN VARCHAR2,
OS_COD_RETORNO        OUT VARCHAR2,
OS_MEN_RETORNO        OUT VARCHAR2,
OS_CURSOR             OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_USUARIO_LOGIN(
IS_USUARIO            IN VARCHAR2,
OS_COD_RETORNO        OUT VARCHAR2,
OS_MEN_RETORNO        OUT VARCHAR2,
OS_CURSOR             OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_USUARIO_TODOS(
IS_ID_EMPRESA          IN NUMBER,
IS_NOMBRE              IN VARCHAR2,
IS_APELLIDO            IN VARCHAR2,
IS_ESTADO              IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_ROL_POR_USUARIO(
IS_USUARIO          IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_PERM_POR_USUARIO(
IS_USUARIO          IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);


PROCEDURE SPS_VERI_SUPER_USUARIO(
IS_USUARIO        IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_USU_DES_BLO(
  IS_ID_EMPRESA          IN VARCHAR2,
  IS_NOMBRE              IN VARCHAR2, 
  IS_ESTADO              IN VARCHAR2,
  OS_COD_RETORNO         OUT VARCHAR2,
  OS_MEN_RETORNO         OUT VARCHAR2,
  OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPU_REGISTRAR_USU_DES_BLO(
  IS_USUARIOS          IN VARCHAR2,
  IS_USUARIO       IN VARCHAR2,
  IS_ESTADO              IN VARCHAR2,
  OS_COD_RETORNO         OUT VARCHAR2,
  OS_MEN_RETORNO         OUT VARCHAR2,
  OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_DETALLE_AUD(
IS_ID_AUDITORIA        IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);


PROCEDURE SPU_ACTUALIZAR_USUARIO_ESTADO(
IS_ID_USUARIO IN NUMBER,
IS_ESTADO IN VARCHAR2,
IS_CONTRASENA IN VARCHAR2,
IS_FECHACAMBIOCLAVE IN TIMESTAMP,
IS_USUARIO_AGR     IN VARCHAR2,
OS_COD_RETORNO     OUT VARCHAR2,
OS_MEN_RETORNO     OUT VARCHAR2
);

/*
==========================
STORE PROCEDURE DE APLICACION
===========================*/

PROCEDURE SPS_CONSULTAR_APLICACIONES_USU(
  IS_ID_EMPRESA IN VARCHAR2,
  OS_COD_RETORNO         OUT VARCHAR2,
  OS_MEN_RETORNO         OUT VARCHAR2,
  OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_APLICACION_DATA(
  IS_TIPO IN NUMBER,
  OS_COD_RETORNO         OUT VARCHAR2,
  OS_MEN_RETORNO         OUT VARCHAR2,
  OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPI_REGISTRAR_APLICACION(
IS_ID_EMPRESA IN NUMBER,
IS_MNEMONICO IN VARCHAR2,
IS_NOMBRE IN VARCHAR2,
IS_DESCRIPCION IN VARCHAR2,
IS_ESTADO IN VARCHAR2,
IS_POLITICA IN VARCHAR2,
IS_USUARIO  IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_COD_ID_APLICACION     OUT NUMBER
);

PROCEDURE SPU_ACTUALIZAR_APLICACION(
IS_ID_APLICACION   IN NUMBER,
IS_NOMBRE       IN VARCHAR2,
IS_DESCRIPCION     IN VARCHAR2,
IS_ESTADO       IN VARCHAR,
IS_POLITICA     IN VARCHAR,
IS_USUARIO       IN VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2
);

PROCEDURE SPD_ELIMINAR_APLICACION(
IS_ID_APLICACION IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);

PROCEDURE SPS_CONSULTAR_APLICACION(
IS_ID_APLICACION       IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPU_ACTIVAR_POLITICA(
IS_ID_APLICACION   IN NUMBER,
IS_ESTADO       IN VARCHAR2,
IS_USUARIO       IN VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2
);

PROCEDURE SPS_CONSULTAR_APLICACION_TODAS(
IS_ID_EMPRESA          IN NUMBER,
IS_NOMBRE              IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_APLICACION_EMP(
IS_ID_EMPRESA           IN VARCHAR2,
OS_COD_RETORNO          OUT VARCHAR2,
OS_MEN_RETORNO          OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_USUARIOS_EMP(
IS_ID_EMPRESA           IN VARCHAR2,
OS_COD_RETORNO          OUT VARCHAR2,
OS_MEN_RETORNO          OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);


PROCEDURE SPS_REG_ROLES_USER_APP(
IS_ROLES               IN VARCHAR2,
IS_APLICACION          IN NUMBER,
IS_USUARIO             IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2
);

PROCEDURE SPS_CONSULTAR_PICKDATA_ROLES(
IS_APLICACION          IN NUMBER,
IS_USUARIO             IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_REG_PERM_ROL_APP(
IS_PERMISOS               IN VARCHAR2,
IS_ROL             IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2
);

PROCEDURE SPS_REG_ROL_X_ROL_APP(
IS_ROLES               IN VARCHAR2,
IS_ROL             IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2
);


/*
==========================
STORE PROCEDURE DE ROL
===========================*/


PROCEDURE SPI_REGISTRAR_ROL(
IS_ID_APLICACION NUMBER,
IS_MNEMONICO   IN VARCHAR2,
IS_NOMBRE     IN VARCHAR2,
IS_DESCRIPCION   IN VARCHAR2,
IS_ESTADO     IN VARCHAR2,
IS_USUARIO     IN VARCHAR2,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_COD_ROL          OUT NUMBER,
OS_EMPRESA          OUT VARCHAR2
);

PROCEDURE SPU_ACTUALIZAR_ROL(
IS_ID_ROL       IN NUMBER,
IS_NOMBRE       IN VARCHAR2,
IS_MNEMONICO     IN VARCHAR2,
IS_DESCRIPCION     IN VARCHAR2,
IS_ESTADO       IN VARCHAR2,
IS_USUARIO      IN VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2,
OS_EMPRESA      OUT VARCHAR2
);

PROCEDURE SPD_ELIMINAR_ROL(
IS_ID_ROL IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);


PROCEDURE SPS_CONSULTAR_ROL(
IS_ROL IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_ROL_TODAS(
IS_ROL IN VARCHAR2,
IS_ID_EMPRESA IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_ROLES(
IS_USUARIO IN VARCHAR2,
IS_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);



PROCEDURE SPS_CONSULTAR_ROL_APLI_DATA(
IS_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_ROL_DATA(
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_PERMISO_DATA(
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_ROL_PADRES(
IS_ROL IN NUMBER,
IS_APLICACION IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

/*
==========================
STORE PROCEDURE DE PERMISO
===========================*/

PROCEDURE SPI_REGISTRAR_PERMISO(
IS_ID_APLICACION   NUMBER,
IS_MNEMONICO     IN VARCHAR2,
IS_NOMBRE       IN VARCHAR2,
IS_DESCRIPCION     IN VARCHAR2,
IS_ESTADO       IN VARCHAR2,
IS_TIPO       IN VARCHAR2,
IS_USUARIO       IN VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2,
OS_COD_ID_PERMISO   OUT NUMBER
);

PROCEDURE SPU_ACTUALIZAR_PERMISO(
IS_ID_PERMISO     IN NUMBER,
IS_NOMBRE       IN VARCHAR2,
IS_MNEMONICO     IN VARCHAR2,
IS_DESCRIPCION     IN VARCHAR2,
IS_ESTADO       IN VARCHAR2,
IS_TIPO       IN VARCHAR2,
IS_USUARIO       IN VARCHAR2,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2
);

PROCEDURE SPD_ELIMINAR_PERMISO(
IS_ID_PERMISO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);

PROCEDURE SPS_CONSULTAR_PERMISO(
IS_PERMISO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_PERMISOS(
IS_EMPRESA IN VARCHAR2,
IS_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_PERMISO_TODAS(
IS_PERMISO IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_PERMISO_POR_ROL(
IS_ROL          IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

/*
==========================
STORE PROCEDURE DE POLITICA
===========================*/

PROCEDURE SPS_CONSULTAR_POLITICAS(
IS_OPCION         IN VARCHAR2,
IS_ID_EMPRESA     IN VARCHAR2,
OS_COD_RETORNO    OUT VARCHAR2,
OS_MEN_RETORNO    OUT VARCHAR2,
OS_CURSOR         OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_POLITICA(
IS_EVENTO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_POLITICA_X_EMP(
IS_ID_EMPRESA          IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_POLITICA_X_APLI(
IS_ID_EMPRESA    IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPS_ACTUALIZAR_POLITICA(
IS_ID_POLITICA IN VARCHAR2,
IS_ID_ATRIBUTO IN VARCHAR2,
IS_ID_EMPRESA  IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
IS_VALOR IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2
);

PROCEDURE SPS_ACTUALIZAR_POLITICA_APP(
IS_ID_POLITICA IN VARCHAR2,
IS_ID_ATRIBUTO IN VARCHAR2,
IS_ID_EMPRESA  IN VARCHAR2,
IS_ID_APLICACION IN VARCHAR2,
IS_VALOR IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2
);



/*
==========================
STORE PROCEDURE DE ATRIBUTO
===========================*/

PROCEDURE SPS_CONSULTAR_ATRIBUTO_EMPRESA(
IS_EMPRESA IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);


PROCEDURE SPS_CONSULTAR_ATRIBUTO_APP(
IS_APLICACION IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

/*
==========================
STORE PROCEDURE BLOQUEO
===========================*/

PROCEDURE SPI_REGISTRAR_BLOQUEO(
IS_USUARIO IN VARCHAR2,
IS_EMPRESA IN VARCHAR2,
IS_ESTADO IN VARCHAR2,
IS_FECHA IN TIMESTAMP,
IS_INTENTOSFALLIDOS IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2

);

PROCEDURE SPU_ACTUALIZAR_BLOQUEO(
IS_USUARIO IN VARCHAR2,
IS_ESTADO IN VARCHAR2,
IS_FECHA IN TIMESTAMP,
IS_INTENTOSFALLIDOS IN NUMBER,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2

);

PROCEDURE SPS_CONSULTAR_BLOQUEO(
IS_USUARIO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

/*
==========================
STORE PROCEDURE CLAVEANTIGUA
===========================*/

PROCEDURE SPS_CONSULTAR_CLAVEANTIGUA(
IS_USUARIO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPI_REGISTRAR_CLAVEANTIGUA(
IS_USUARIO IN VARCHAR2,
IS_EMPRESA IN VARCHAR2,
IS_PASSWORDS IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2

);

PROCEDURE SPU_ACTUALIZAR_CLAVEANTIGUA(
PASSWORDS IN VARCHAR2,
IS_USUARIO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2

);

/*
==========================
STORE PROCEDURE DE LLAVE
===========================*/

PROCEDURE SPI_REGISTRAR_LLAVE(
IS_NOMBRE IN VARCHAR2,
IS_VALOR_NUEVO IN VARCHAR2,
IS_TIPO_LLAVE IN VARCHAR2,
IS_TIPO_GENERACION IN VARCHAR2,
IS_ESTADO IN VARCHAR,
IS_AUD_USUARIO_CREACION IN VARCHAR2,
IS_AUD_FECHA_CREACION IN TIMESTAMP,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2

);

PROCEDURE SPU_ACTUALIZAR_LLAVE(
IS_ID_LLAVE IN NUMBER,
IS_NOMBRE IN VARCHAR2,
IS_VALOR_NUEVO IN VARCHAR2,
IS_TIPO_LLAVE IN VARCHAR2,
IS_TIPO_GENERACION IN VARCHAR2,
IS_ESTADO IN VARCHAR,
IS_AUD_USUARIO_MODIFICACION IN VARCHAR2,
IS_AUD_FECHA_MODIFICACION IN TIMESTAMP,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2

);

PROCEDURE SPD_ELIMINAR_LLAVE(
IS_ID_LLAVE IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);

PROCEDURE SPS_CONSULTAR_LLAVE_SEGUN_TIPO(
IS_TIPO_LLAVE IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);


/*
==========================
STORE PROCEDURE HORARIO
===========================*/
PROCEDURE SPS_CONSULTAR_HORARIO(
IS_HORARIO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR);


PROCEDURE SPS_CONSULTAR_HORARIO_EMPRESA(
IS_EMPRESA IN NUMBER,
IS_CODIGO_HORARIO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_HORARIO_TODAS(
IS_NOMBRE IN VARCHAR2,
IS_TIPO IN VARCHAR2,
IS_EMPRESA IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

PROCEDURE SPI_REGISTRAR_HORARIO(
IS_ID_APLICACION  IN NUMBER,
IS_ID_EMPRESA     IN NUMBER,
IS_ID_USUARIO     IN NUMBER,
IS_TIPO       IN VARCHAR2,
IS_MNEMONICO     IN VARCHAR2,
IS_NOMBRE       IN VARCHAR2,
IS_MAC         IN VARCHAR2,
IS_USUARIO      IN VARCHAR2,
OS_ID_HORARIO       OUT NUMBER,
OS_COD_RETORNO      OUT VARCHAR2,
OS_MEN_RETORNO      OUT VARCHAR2
);

PROCEDURE SPI_REGISTRAR_HORARIO_DET(
IS_ID_HORARIO IN NUMBER,
IS_DOMINGO IN NUMBER,
IS_HORA_FIN IN VARCHAR2,
IS_HORA_INICIO IN VARCHAR,
IS_JUEVES IN NUMBER,
IS_LUNES IN NUMBER,
IS_MARTES IN NUMBER,
IS_MIERCOLES IN NUMBER,
IS_POR_DIA IN NUMBER,
IS_POR_HORA IN NUMBER,
IS_SABADO IN NUMBER,
IS_VIERNES IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);

PROCEDURE SPU_ACTUALIZAR_HORARIO(
IS_ID_APLICACION NUMBER,
IS_ID_EMPRESA    NUMBER,
IS_ID_USUARIO    IN VARCHAR2,
IS_TIPO      IN VARCHAR2,
IS_MNEMONICO    IN VARCHAR2,
IS_NOMBRE      IN VARCHAR2,
IS_MAC        IN VARCHAR2,
IS_USUARIO       IN VARCHAR2,
IS_ID_HORARIO    IN NUMBER,
OS_COD_RETORNO   OUT VARCHAR2,
OS_MEN_RETORNO   OUT VARCHAR2
);

PROCEDURE SPU_ACTUALIZAR_HORARIO_DET(
IS_ID_HORARIO IN NUMBER,
IS_ID_DETALLE IN NUMBER,
IS_DOMINGO IN NUMBER,
IS_HORA_FIN IN VARCHAR2,
IS_HORA_INICIO IN VARCHAR,
IS_JUEVES IN NUMBER,
IS_LUNES IN NUMBER,
IS_MARTES IN NUMBER,
IS_MIERCOLES IN NUMBER,
IS_POR_DIA IN NUMBER,
IS_POR_HORA IN NUMBER,
IS_SABADO IN NUMBER,
IS_VIERNES IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);

PROCEDURE SPD_ELIMINAR_HORARIO(
IS_ID_HORARIO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);


PROCEDURE SPD_ELIMINAR_HORARIO_DET(
IS_ID_HORARIO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2
);

PROCEDURE SPS_OBTENER_CODIGO_HORARIO(
IS_TIPO IN VARCHAR2,
IS_ID_DATA IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR);

PROCEDURE SPS_CONSULTAR_HORARIO_DET(
IS_HORARIO IN NUMBER,
OS_COD_RETORNO           OUT VARCHAR2,
OS_MEN_RETORNO           OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR);

PROCEDURE SPS_CONSULTAR_USUARIO_ADAPTER(
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);


/*
==========================
STORE PROCEDURE IMPORTAR
===========================*/



PROCEDURE SPS_CONSULTAR_ROL_X_APP(
  IS_ID_APLICACION  IN VARCHAR2,
  OS_COD_RETORNO    OUT VARCHAR2,
  OS_MEN_RETORNO    OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_APP(																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									
  IS_ID_APLICACION  IN VARCHAR2,
  OS_COD_RETORNO    OUT VARCHAR2,
  OS_MEN_RETORNO    OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_APP_EMP(
IS_APLICACION        IN VARCHAR2,
IS_EMPRESA    IN VARCHAR2,
OS_COD_RETORNO          OUT VARCHAR2,
OS_MEN_RETORNO          OUT VARCHAR2,
OS_CURSOR               OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_ROL_USUARIO(
  IS_ID_EMPRESA     IN VARCHAR2,
  IS_ID_USUARIO     IN VARCHAR2,
  OS_COD_RETORNO    OUT VARCHAR2,
  OS_MEN_RETORNO    OUT VARCHAR2,
  OS_CURSOR         OUT T_CURSOR
);

PROCEDURE SPS_CONSULTAR_PERMISO_IMPORT(
IS_ID_APLICACION IN VARCHAR2,
IS_MNEMONICO IN VARCHAR2,
OS_COD_RETORNO         OUT VARCHAR2,
OS_MEN_RETORNO         OUT VARCHAR2,
OS_CURSOR              OUT T_CURSOR
);

FUNCTION FUN_EMPRESA_X_APLICACION(
IS_ID_APLICACION IN NUMBER) RETURN VARCHAR2;

END PKG_SCA;
